/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

CBlowfish *__thiscall CBlowfish::CBlowfish(CBlowfish *__hidden this); // idb
void __thiscall CBlowfish::GenerateSubkeys(CBlowfish *__hidden this, char *); // idb
void __thiscall CBlowfish::BF_En(CBlowfish *__hidden this, union BFWord *, union BFWord *); // idb
void __thiscall CBlowfish::Reset(CBlowfish *__hidden this); // idb
void __thiscall CBlowfish::SetPassword(CBlowfish *__hidden this, char *); // idb
void __thiscall CBlowfish::Encrypt(CBlowfish *__hidden this, union BFWord *, unsigned int); // idb
void __thiscall CBlowfish::Decrypt(CBlowfish *__hidden this, union BFWord *, unsigned int); // idb
void __thiscall CBlowfish::BF_De(CBlowfish *__hidden this, union BFWord *, union BFWord *); // idb

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN PA_Init; // weak
_UNKNOWN SB_Init; // weak
_UNKNOWN unk_1047; // weak


//----- (00001048) --------------------------------------------------------
CBlowfish *__thiscall CBlowfish::CBlowfish(CBlowfish *this)
{
  CBlowfish::Reset(this);
  return this;
}

//----- (00001058) --------------------------------------------------------
void __thiscall CBlowfish::GenerateSubkeys(CBlowfish *this, char *a2)
{
  char *v2; // ebp
  unsigned int v4; // kr04_4
  unsigned int v5; // ecx
  CBlowfish *v6; // ebx
  unsigned int v7; // esi
  unsigned int v8; // edi
  unsigned __int16 v9; // bx
  unsigned int v10; // ebx
  int v11; // edi
  char v12; // dl
  CBlowfish *v13; // edi
  CBlowfish *v14; // esi
  int v15; // ebx
  int v16; // eax
  int *v17; // esi
  int v18; // ebp
  int v19; // ebx
  int v20; // ecx
  int v21; // [esp+8h] [ebp-8h] BYREF
  CBlowfish *v22; // [esp+Ch] [ebp-4h]

  v2 = a2;
  v22 = this;
  v4 = strlen(a2) + 1;
  v5 = v4 - 1;
  if ( v4 != 1 )
  {
    a2 = (char *)this;
    v6 = this;
    v7 = 0;
    v21 = 18;
    do
    {
      v8 = ((unsigned int)v6 & 0xFFFFFF | (v2[v7 % v5] << 24)) & 0xFF00FFFF;
      LOBYTE(v9) = 0;
      HIBYTE(v9) = v2[(v7 + 2) % v5];
      v10 = (((unsigned __int8)v2[(v7 + 1) % v5] << 16) | v8) & 0xFFFF00FF | v9;
      v11 = *(_DWORD *)a2;
      v12 = v2[(v7 + 3) % v5];
      a2 += 4;
      v6 = (CBlowfish *)((unsigned __int8)(v10 ^ v12) ^ v10);
      v7 += 4;
      *((_DWORD *)a2 - 1) = (unsigned int)v6 ^ v11;
      --v21;
    }
    while ( v21 );
    v13 = v22;
    v21 = 0;
    a2 = 0;
    v14 = v22;
    v15 = 9;
    do
    {
      CBlowfish::BF_En(v13, (union BFWord *)&a2, (union BFWord *)&v21);
      v16 = v21;
      *(_DWORD *)v14 = a2;
      *((_DWORD *)v14 + 1) = v16;
      v14 = (CBlowfish *)((char *)v14 + 8);
      --v15;
    }
    while ( v15 );
    v17 = (int *)((char *)v13 + 76);
    v18 = 4;
    do
    {
      v19 = 128;
      do
      {
        CBlowfish::BF_En(v13, (union BFWord *)&a2, (union BFWord *)&v21);
        v20 = v21;
        *(v17 - 1) = (int)a2;
        *v17 = v20;
        v17 += 2;
        --v19;
      }
      while ( v19 );
      --v18;
    }
    while ( v18 );
  }
}

//----- (00001188) --------------------------------------------------------
void __thiscall CBlowfish::BF_En(CBlowfish *this, union BFWord *a2, union BFWord *a3)
{
  unsigned int v4; // edx
  unsigned int v5; // eax
  unsigned int v6; // edx
  unsigned int v7; // eax
  unsigned int v8; // edx
  unsigned int v9; // eax
  unsigned int v10; // edx
  unsigned int v11; // eax
  unsigned int v12; // edx
  unsigned int v13; // eax
  unsigned int v14; // edx
  unsigned int v15; // eax
  unsigned int v16; // edx
  unsigned int v17; // eax
  unsigned int v18; // edx
  int v19; // edx
  unsigned int v20; // [esp+14h] [ebp+4h]

  v4 = *(_DWORD *)this ^ *(_DWORD *)a2;
  v5 = *(_DWORD *)a3 ^ *((_DWORD *)this + 1) ^ (*((_DWORD *)this + (unsigned __int8)v4 + 786)
                                              + (*((_DWORD *)this + BYTE1(v4) + 530) ^ (*((_DWORD *)this
                                                                                        + HIBYTE(v4)
                                                                                        + 18)
                                                                                      + *((_DWORD *)this
                                                                                        + BYTE2(v4)
                                                                                        + 274))));
  v6 = *((_DWORD *)this + 2) ^ (*((_DWORD *)this + (unsigned __int8)v5 + 786)
                              + (*((_DWORD *)this + BYTE1(v5) + 530) ^ (*((_DWORD *)this + HIBYTE(v5) + 18)
                                                                      + *((_DWORD *)this + BYTE2(v5) + 274)))) ^ v4;
  v7 = *((_DWORD *)this + 3) ^ (*((_DWORD *)this + (unsigned __int8)v6 + 786)
                              + (*((_DWORD *)this + BYTE1(v6) + 530) ^ (*((_DWORD *)this + HIBYTE(v6) + 18)
                                                                      + *((_DWORD *)this + BYTE2(v6) + 274)))) ^ v5;
  v8 = *((_DWORD *)this + 4) ^ (*((_DWORD *)this + (unsigned __int8)v7 + 786)
                              + (*((_DWORD *)this + BYTE1(v7) + 530) ^ (*((_DWORD *)this + HIBYTE(v7) + 18)
                                                                      + *((_DWORD *)this + BYTE2(v7) + 274)))) ^ v6;
  v9 = *((_DWORD *)this + 5) ^ (*((_DWORD *)this + (unsigned __int8)v8 + 786)
                              + (*((_DWORD *)this + BYTE1(v8) + 530) ^ (*((_DWORD *)this + HIBYTE(v8) + 18)
                                                                      + *((_DWORD *)this + BYTE2(v8) + 274)))) ^ v7;
  v10 = *((_DWORD *)this + 6) ^ (*((_DWORD *)this + (unsigned __int8)v9 + 786)
                               + (*((_DWORD *)this + BYTE1(v9) + 530) ^ (*((_DWORD *)this + HIBYTE(v9) + 18)
                                                                       + *((_DWORD *)this + BYTE2(v9) + 274)))) ^ v8;
  v11 = *((_DWORD *)this + 7) ^ (*((_DWORD *)this + (unsigned __int8)v10 + 786)
                               + (*((_DWORD *)this + BYTE1(v10) + 530) ^ (*((_DWORD *)this + HIBYTE(v10) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v10) + 274)))) ^ v9;
  v12 = *((_DWORD *)this + 8) ^ (*((_DWORD *)this + (unsigned __int8)v11 + 786)
                               + (*((_DWORD *)this + BYTE1(v11) + 530) ^ (*((_DWORD *)this + HIBYTE(v11) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v11) + 274)))) ^ v10;
  v13 = *((_DWORD *)this + 9) ^ (*((_DWORD *)this + (unsigned __int8)v12 + 786)
                               + (*((_DWORD *)this + BYTE1(v12) + 530) ^ (*((_DWORD *)this + HIBYTE(v12) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v12) + 274)))) ^ v11;
  v14 = *((_DWORD *)this + 10) ^ (*((_DWORD *)this + (unsigned __int8)v13 + 786)
                                + (*((_DWORD *)this + BYTE1(v13) + 530) ^ (*((_DWORD *)this + HIBYTE(v13) + 18)
                                                                         + *((_DWORD *)this + BYTE2(v13) + 274)))) ^ v12;
  v15 = *((_DWORD *)this + 11) ^ (*((_DWORD *)this + (unsigned __int8)v14 + 786)
                                + (*((_DWORD *)this + BYTE1(v14) + 530) ^ (*((_DWORD *)this + HIBYTE(v14) + 18)
                                                                         + *((_DWORD *)this + BYTE2(v14) + 274)))) ^ v13;
  v16 = *((_DWORD *)this + 12) ^ (*((_DWORD *)this + (unsigned __int8)v15 + 786)
                                + (*((_DWORD *)this + BYTE1(v15) + 530) ^ (*((_DWORD *)this + HIBYTE(v15) + 18)
                                                                         + *((_DWORD *)this + BYTE2(v15) + 274)))) ^ v14;
  v17 = *((_DWORD *)this + 13) ^ (*((_DWORD *)this + (unsigned __int8)v16 + 786)
                                + (*((_DWORD *)this + BYTE1(v16) + 530) ^ (*((_DWORD *)this + HIBYTE(v16) + 18)
                                                                         + *((_DWORD *)this + BYTE2(v16) + 274)))) ^ v15;
  v18 = *((_DWORD *)this + 14) ^ (*((_DWORD *)this + (unsigned __int8)v17 + 786)
                                + (*((_DWORD *)this + BYTE1(v17) + 530) ^ (*((_DWORD *)this + HIBYTE(v17) + 18)
                                                                         + *((_DWORD *)this + BYTE2(v17) + 274)))) ^ v16;
  v20 = *((_DWORD *)this + 15) ^ (*((_DWORD *)this + (unsigned __int8)v18 + 786)
                                + (*((_DWORD *)this + BYTE1(v18) + 530) ^ (*((_DWORD *)this + HIBYTE(v18) + 18)
                                                                         + *((_DWORD *)this + BYTE2(v18) + 274)))) ^ v17;
  v19 = *((_DWORD *)this + 16) ^ (*((_DWORD *)this + (unsigned __int8)v20 + 786)
                                + (*((_DWORD *)this + BYTE1(v20) + 530) ^ (*((_DWORD *)this + HIBYTE(v20) + 18)
                                                                         + *((_DWORD *)this + BYTE2(v20) + 274)))) ^ v18;
  *(_DWORD *)a2 = v20 ^ *((_DWORD *)this + 17);
  *(_DWORD *)a3 = v19;
}

//----- (00001598) --------------------------------------------------------
void __thiscall CBlowfish::Reset(CBlowfish *this)
{
  CBlowfish *v1; // eax
  int v2; // esi
  int *v3; // eax
  _DWORD *v4; // ecx
  int v5; // edx
  int v6; // esi

  v1 = this;
  v2 = 18;
  do
  {
    *(_DWORD *)v1 = *(_DWORD *)((char *)v1 + &PA_Init - (_UNKNOWN *)this);
    v1 = (CBlowfish *)((char *)v1 + 4);
    --v2;
  }
  while ( v2 );
  v3 = (int *)&SB_Init;
  v4 = (_DWORD *)((char *)this + 72);
  do
  {
    v5 = 256;
    do
    {
      v6 = *v3++;
      *v4++ = v6;
      --v5;
    }
    while ( v5 );
  }
  while ( v3 < (int *)((char *)&unk_1047 + 1) );
}

//----- (000015D8) --------------------------------------------------------
void __thiscall CBlowfish::SetPassword(CBlowfish *this, char *a2)
{
  if ( a2 )
  {
    if ( strlen(a2) )
    {
      CBlowfish::Reset(this);
      CBlowfish::GenerateSubkeys(this, a2);
    }
  }
}

//----- (00001608) --------------------------------------------------------
void __thiscall CBlowfish::Encrypt(CBlowfish *this, union BFWord *a2, unsigned int a3)
{
  unsigned int i; // edi

  for ( i = a3 >> 3; i; --i )
  {
    CBlowfish::BF_En(this, a2, (union BFWord *)((char *)a2 + 4));
    a2 = (union BFWord *)((char *)a2 + 8);
  }
}

//----- (00001638) --------------------------------------------------------
void __thiscall CBlowfish::Decrypt(CBlowfish *this, union BFWord *a2, unsigned int a3)
{
  unsigned int i; // edi

  for ( i = a3 >> 3; i; --i )
  {
    CBlowfish::BF_De(this, a2, (union BFWord *)((char *)a2 + 4));
    a2 = (union BFWord *)((char *)a2 + 8);
  }
}

//----- (00001668) --------------------------------------------------------
void __thiscall CBlowfish::BF_De(CBlowfish *this, union BFWord *a2, union BFWord *a3)
{
  unsigned int v4; // edx
  unsigned int v5; // eax
  unsigned int v6; // edx
  unsigned int v7; // eax
  unsigned int v8; // edx
  unsigned int v9; // eax
  unsigned int v10; // edx
  unsigned int v11; // eax
  unsigned int v12; // edx
  unsigned int v13; // eax
  unsigned int v14; // edx
  unsigned int v15; // eax
  unsigned int v16; // edx
  unsigned int v17; // eax
  unsigned int v18; // edx
  int v19; // edx
  unsigned int v20; // [esp+14h] [ebp+4h]

  v4 = *(_DWORD *)a2 ^ *((_DWORD *)this + 17);
  v5 = *(_DWORD *)a3 ^ *((_DWORD *)this + 16) ^ (*((_DWORD *)this + (unsigned __int8)v4 + 786)
                                               + (*((_DWORD *)this + BYTE1(v4) + 530) ^ (*((_DWORD *)this
                                                                                         + HIBYTE(v4)
                                                                                         + 18)
                                                                                       + *((_DWORD *)this
                                                                                         + BYTE2(v4)
                                                                                         + 274))));
  v6 = *((_DWORD *)this + 15) ^ (*((_DWORD *)this + (unsigned __int8)v5 + 786)
                               + (*((_DWORD *)this + BYTE1(v5) + 530) ^ (*((_DWORD *)this + HIBYTE(v5) + 18)
                                                                       + *((_DWORD *)this + BYTE2(v5) + 274)))) ^ v4;
  v7 = *((_DWORD *)this + 14) ^ (*((_DWORD *)this + (unsigned __int8)v6 + 786)
                               + (*((_DWORD *)this + BYTE1(v6) + 530) ^ (*((_DWORD *)this + HIBYTE(v6) + 18)
                                                                       + *((_DWORD *)this + BYTE2(v6) + 274)))) ^ v5;
  v8 = *((_DWORD *)this + 13) ^ (*((_DWORD *)this + (unsigned __int8)v7 + 786)
                               + (*((_DWORD *)this + BYTE1(v7) + 530) ^ (*((_DWORD *)this + HIBYTE(v7) + 18)
                                                                       + *((_DWORD *)this + BYTE2(v7) + 274)))) ^ v6;
  v9 = *((_DWORD *)this + 12) ^ (*((_DWORD *)this + (unsigned __int8)v8 + 786)
                               + (*((_DWORD *)this + BYTE1(v8) + 530) ^ (*((_DWORD *)this + HIBYTE(v8) + 18)
                                                                       + *((_DWORD *)this + BYTE2(v8) + 274)))) ^ v7;
  v10 = *((_DWORD *)this + 11) ^ (*((_DWORD *)this + (unsigned __int8)v9 + 786)
                                + (*((_DWORD *)this + BYTE1(v9) + 530) ^ (*((_DWORD *)this + HIBYTE(v9) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v9) + 274)))) ^ v8;
  v11 = *((_DWORD *)this + 10) ^ (*((_DWORD *)this + (unsigned __int8)v10 + 786)
                                + (*((_DWORD *)this + BYTE1(v10) + 530) ^ (*((_DWORD *)this + HIBYTE(v10) + 18)
                                                                         + *((_DWORD *)this + BYTE2(v10) + 274)))) ^ v9;
  v12 = *((_DWORD *)this + 9) ^ (*((_DWORD *)this + (unsigned __int8)v11 + 786)
                               + (*((_DWORD *)this + BYTE1(v11) + 530) ^ (*((_DWORD *)this + HIBYTE(v11) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v11) + 274)))) ^ v10;
  v13 = *((_DWORD *)this + 8) ^ (*((_DWORD *)this + (unsigned __int8)v12 + 786)
                               + (*((_DWORD *)this + BYTE1(v12) + 530) ^ (*((_DWORD *)this + HIBYTE(v12) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v12) + 274)))) ^ v11;
  v14 = *((_DWORD *)this + 7) ^ (*((_DWORD *)this + (unsigned __int8)v13 + 786)
                               + (*((_DWORD *)this + BYTE1(v13) + 530) ^ (*((_DWORD *)this + HIBYTE(v13) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v13) + 274)))) ^ v12;
  v15 = *((_DWORD *)this + 6) ^ (*((_DWORD *)this + (unsigned __int8)v14 + 786)
                               + (*((_DWORD *)this + BYTE1(v14) + 530) ^ (*((_DWORD *)this + HIBYTE(v14) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v14) + 274)))) ^ v13;
  v16 = *((_DWORD *)this + 5) ^ (*((_DWORD *)this + (unsigned __int8)v15 + 786)
                               + (*((_DWORD *)this + BYTE1(v15) + 530) ^ (*((_DWORD *)this + HIBYTE(v15) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v15) + 274)))) ^ v14;
  v17 = *((_DWORD *)this + 4) ^ (*((_DWORD *)this + (unsigned __int8)v16 + 786)
                               + (*((_DWORD *)this + BYTE1(v16) + 530) ^ (*((_DWORD *)this + HIBYTE(v16) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v16) + 274)))) ^ v15;
  v18 = *((_DWORD *)this + 3) ^ (*((_DWORD *)this + (unsigned __int8)v17 + 786)
                               + (*((_DWORD *)this + BYTE1(v17) + 530) ^ (*((_DWORD *)this + HIBYTE(v17) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v17) + 274)))) ^ v16;
  v20 = *((_DWORD *)this + 2) ^ (*((_DWORD *)this + (unsigned __int8)v18 + 786)
                               + (*((_DWORD *)this + BYTE1(v18) + 530) ^ (*((_DWORD *)this + HIBYTE(v18) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v18) + 274)))) ^ v17;
  v19 = *((_DWORD *)this + 1) ^ (*((_DWORD *)this + (unsigned __int8)v20 + 786)
                               + (*((_DWORD *)this + BYTE1(v20) + 530) ^ (*((_DWORD *)this + HIBYTE(v20) + 18)
                                                                        + *((_DWORD *)this + BYTE2(v20) + 274)))) ^ v18;
  *(_DWORD *)a2 = v20 ^ *(_DWORD *)this;
  *(_DWORD *)a3 = v19;
}

// nfuncs=8 queued=8 decompiled=8 lumina nreq=0 worse=0 better=0
// ALL OK, 8 function(s) have been successfully decompiled
