/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

CCrc32Static *__thiscall CCrc32Static::CCrc32Static(CCrc32Static *this);
CCrc32Static *__thiscall CCrc32Static::`scalar deleting destructor'(CCrc32Static *this, char a2);
void __thiscall CCrc32Static::~CCrc32Static(CCrc32Static *__hidden this); // idb
unsigned int __stdcall CCrc32Static::BufferCrc32(const unsigned __int8 *, unsigned int, unsigned int *); // idb
DWORD __stdcall CCrc32Static::FileCrc32Win32(LPCSTR lpFileName, unsigned int *a2);
// void __cdecl operator delete(void *); idb
// BOOL __stdcall CloseHandle(HANDLE hObject);
// BOOL __stdcall ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// DWORD __stdcall GetLastError();
// HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);

//-------------------------------------------------------------------------
// Data declarations

unsigned int *CCrc32Static::s_arrdwCrc32Table = &CCrc32Static::s_arrdwCrc32Table; // weak
void *CCrc32Static::`vftable' = &CCrc32Static::`vector deleting destructor'; // weak


//----- (00000400) --------------------------------------------------------
CCrc32Static *__thiscall CCrc32Static::CCrc32Static(CCrc32Static *this)
{
  CCrc32Static *result; // eax

  result = this;
  *(_DWORD *)this = &CCrc32Static::`vftable';
  return result;
}
// 410: using guessed type void *CCrc32Static::`vftable';

//----- (00000414) --------------------------------------------------------
CCrc32Static *__thiscall CCrc32Static::`scalar deleting destructor'(CCrc32Static *this, char a2)
{
  CCrc32Static::~CCrc32Static(this);
  if ( (a2 & 1) != 0 )
    operator delete(this);
  return this;
}

//----- (00000434) --------------------------------------------------------
void __thiscall CCrc32Static::~CCrc32Static(CCrc32Static *this)
{
  *(_DWORD *)this = &CCrc32Static::`vftable';
}
// 410: using guessed type void *CCrc32Static::`vftable';

//----- (00000444) --------------------------------------------------------
unsigned int __stdcall CCrc32Static::BufferCrc32(const unsigned __int8 *a1, unsigned int a2, unsigned int *a3)
{
  unsigned int v3; // ecx
  unsigned int v4; // edx

  v3 = 0;
  for ( *a3 = -1; v3 < a2; *a3 = v4 )
    v4 = (*a3 >> 8) ^ (unsigned int)(&CCrc32Static::s_arrdwCrc32Table)[(unsigned __int8)*a3 ^ a1[v3++]];
  *a3 = ~*a3;
  return 0;
}
// 0: using guessed type unsigned int *CCrc32Static::s_arrdwCrc32Table;

//----- (00000494) --------------------------------------------------------
DWORD __stdcall CCrc32Static::FileCrc32Win32(LPCSTR lpFileName, unsigned int *a2)
{
  HANDLE v2; // eax
  void *v3; // ebp
  DWORD v4; // edi
  DWORD v5; // ecx
  unsigned int v6; // edx
  DWORD result; // eax
  DWORD v8; // [esp+8h] [ebp-1008h]
  DWORD NumberOfBytesRead; // [esp+Ch] [ebp-1004h] BYREF
  char Buffer[4096]; // [esp+10h] [ebp-1000h] BYREF

  v8 = 0;
  *a2 = -1;
  v2 = CreateFileA(lpFileName, 0x80000000, 1u, 0, 3u, 0x8000027u, 0);
  v3 = v2;
  if ( v2 == (HANDLE)-1 )
  {
    v8 = GetLastError();
LABEL_9:
    CloseHandle(v3);
    goto LABEL_10;
  }
  if ( ReadFile(v2, Buffer, 0x1000u, &NumberOfBytesRead, 0) )
  {
    do
    {
      v4 = NumberOfBytesRead;
      if ( !NumberOfBytesRead )
        break;
      v5 = 0;
      do
      {
        v6 = (*a2 >> 8) ^ (unsigned int)(&CCrc32Static::s_arrdwCrc32Table)[(unsigned __int8)*a2 ^ (unsigned __int8)Buffer[v5++]];
        *a2 = v6;
      }
      while ( v5 < v4 );
    }
    while ( ReadFile(v3, Buffer, 0x1000u, &NumberOfBytesRead, 0) );
  }
  if ( v3 )
    goto LABEL_9;
LABEL_10:
  result = v8;
  *a2 = ~*a2;
  return result;
}
// 512: conditional instruction was optimized away because of '%NumberOfBytesRead.4!=0'
// 0: using guessed type unsigned int *CCrc32Static::s_arrdwCrc32Table;

// nfuncs=11 queued=5 decompiled=5 lumina nreq=0 worse=0 better=0
// ALL OK, 5 function(s) have been successfully decompiled
