/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __stdcall _AhnHS_Initialize(LPCSTR lpLibFileName, int (__stdcall *)(int, int, void *), int, const char *, unsigned int); // idb
int __stdcall _AhnHS_StartService(); // idb
int __stdcall _AhnHS_StopService(); // idb
int __stdcall _AhnHS_PauseService(unsigned int); // idb
int __stdcall _AhnHS_ResumeService(unsigned int); // idb
int __stdcall _AhnHS_Uninitialize(); // idb
int __stdcall _AhnHS_CreateProcess(const char *, char *, struct _SECURITY_ATTRIBUTES *, struct _SECURITY_ATTRIBUTES *, int, unsigned int, void *, const char *, struct _STARTUPINFOA *, struct _PROCESS_INFORMATION *); // idb
// uintptr_t __cdecl _beginthreadex(void *Security, unsigned int StackSize, _beginthreadex_proc_type StartAddress, void *ArgList, unsigned int InitFlag, unsigned int *ThrdAddr);
// unsigned int __stdcall FileChangeMoniterThreadProc(void *); idb
// HANDLE __stdcall CreateEventA(LPSECURITY_ATTRIBUTES lpEventAttributes, BOOL bManualReset, BOOL bInitialState, LPCSTR lpName);
// void *__cdecl malloc(size_t Size);
// FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName);
// int __stdcall IsValidDLLFile(const char *); idb
// HMODULE __stdcall LoadLibraryA(LPCSTR lpLibFileName);
// void __cdecl srand(unsigned int Seed);
// DWORD __stdcall GetTickCount();
// BOOL __stdcall CloseHandle(HANDLE hObject);
// BOOL __stdcall SetEvent(HANDLE hEvent);

//-------------------------------------------------------------------------
// Data declarations

HMODULE g_hInstLib; // idb
HANDLE g_hFileChangeEvent; // idb
_UNKNOWN loc_9; // weak
_UNKNOWN loc_A; // weak
_UNKNOWN loc_B; // weak


//----- (00000008) --------------------------------------------------------
int __stdcall _AhnHS_Initialize(LPCSTR lpLibFileName, int (__stdcall *a2)(int, int, void *), int a3, const char *a4, unsigned int a5)
{
  unsigned int v5; // eax
  FARPROC (__stdcall *v6)(HMODULE, LPCSTR); // edi
  FARPROC v7; // esi
  int (*v8)(void); // eax
  int result; // eax
  int v10; // ebp
  char *v11; // ebx
  unsigned int ThrdAddr; // [esp+14h] [ebp-4h] BYREF

  ThrdAddr = 0;
  v5 = GetTickCount();
  srand(v5);
  g_hInstLib = LoadLibraryA(lpLibFileName);
  if ( !g_hInstLib )
    return 257;
  if ( !IsValidDLLFile(lpLibFileName) )
    return 257;
  v6 = GetProcAddress;
  v7 = GetProcAddress(g_hInstLib, (LPCSTR)&g_hInstLib + 1);
  v8 = v6(g_hInstLib, (LPCSTR)&loc_A);
  if ( !v8 || !v7 )
    return 257;
  result = v8();
  if ( !result )
  {
    v10 = ((int (__stdcall *)(int (__stdcall *)(int, int, void *), int, const char *, unsigned int))v7)(a2, a3, a4, a5);
    if ( !v10 )
    {
      v11 = (char *)malloc(0x20Cu);
      *(_DWORD *)v11 = a2;
      strcpy(v11 + 4, lpLibFileName);
      g_hFileChangeEvent = CreateEventA(0, 0, 0, "{5CF594FA-1219-479b-9D5F-F4FC8744E34F}");
      _beginthreadex(0, 0, (_beginthreadex_proc_type)&FileChangeMoniterThreadProc, v11, 0, &ThrdAddr);
    }
    result = v10;
  }
  return result;
}

//----- (00000140) --------------------------------------------------------
int __stdcall _AhnHS_StartService()
{
  int result; // eax
  int (*v1)(void); // eax

  if ( !g_hInstLib )
    return 3;
  v1 = GetProcAddress(g_hInstLib, (LPCSTR)&g_hInstLib + 2);
  if ( v1 )
    result = v1();
  else
    result = 257;
  return result;
}

//----- (00000170) --------------------------------------------------------
int __stdcall _AhnHS_StopService()
{
  int result; // eax
  int (*v1)(void); // eax

  if ( !g_hInstLib )
    return 3;
  v1 = GetProcAddress(g_hInstLib, (LPCSTR)&g_hInstLib + 3);
  if ( v1 )
    result = v1();
  else
    result = 257;
  return result;
}

//----- (000001A0) --------------------------------------------------------
int __stdcall _AhnHS_PauseService(unsigned int a1)
{
  int result; // eax
  FARPROC v2; // eax

  if ( !g_hInstLib )
    return 3;
  v2 = GetProcAddress(g_hInstLib, (LPCSTR)_AhnHS_Initialize);
  if ( v2 )
    result = ((int (__stdcall *)(unsigned int))v2)(a1);
  else
    result = 257;
  return result;
}

//----- (000001D0) --------------------------------------------------------
int __stdcall _AhnHS_ResumeService(unsigned int a1)
{
  int result; // eax
  FARPROC v2; // eax

  if ( !g_hInstLib )
    return 3;
  v2 = GetProcAddress(g_hInstLib, (LPCSTR)&loc_9);
  if ( v2 )
    result = ((int (__stdcall *)(unsigned int))v2)(a1);
  else
    result = 257;
  return result;
}

//----- (00000200) --------------------------------------------------------
int __stdcall _AhnHS_Uninitialize()
{
  int (*v1)(void); // eax
  int v2; // esi

  if ( !g_hInstLib )
    return 3;
  v1 = GetProcAddress(g_hInstLib, (LPCSTR)&g_hFileChangeEvent);
  if ( !v1 )
    return 257;
  v2 = v1();
  if ( !v2 )
  {
    g_hInstLib = 0;
    SetEvent(g_hFileChangeEvent);
    CloseHandle(g_hFileChangeEvent);
    g_hFileChangeEvent = 0;
  }
  return v2;
}

//----- (00000260) --------------------------------------------------------
int __stdcall _AhnHS_CreateProcess(const char *a1, char *a2, struct _SECURITY_ATTRIBUTES *a3, struct _SECURITY_ATTRIBUTES *a4, int a5, unsigned int a6, void *a7, const char *a8, struct _STARTUPINFOA *a9, struct _PROCESS_INFORMATION *a10)
{
  int result; // eax
  FARPROC v11; // eax

  if ( !g_hInstLib )
    return 3;
  v11 = GetProcAddress(g_hInstLib, (LPCSTR)&loc_B);
  if ( v11 )
    result = ((int (__stdcall *)(const char *, char *, struct _SECURITY_ATTRIBUTES *, struct _SECURITY_ATTRIBUTES *, int, unsigned int, void *, const char *, struct _STARTUPINFOA *, struct _PROCESS_INFORMATION *))v11)(
               a1,
               a2,
               a3,
               a4,
               a5,
               a6,
               a7,
               a8,
               a9,
               a10);
  else
    result = 257;
  return result;
}

// nfuncs=17 queued=7 decompiled=7 lumina nreq=0 worse=0 better=0
// ALL OK, 7 function(s) have been successfully decompiled
