/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

LPSTR __stdcall lstrcatn(LPCSTR lpString, LPCSTR lpString2, int a3);
int __stdcall SetFullPath(LPSTR lpString1, int iMaxLength, LPCSTR lpString2, LPCSTR); // idb
int __stdcall VfxGetAppPath(LPSTR lpString1, unsigned int *); // idb
unsigned int __stdcall GetUpdateResult(); // idb
int __stdcall SetUpdateResult(unsigned int a1);
// LPSTR __stdcall lstrcpynA(LPSTR lpString1, LPCSTR lpString2, int iMaxLength);
// int __stdcall lstrlenA(LPCSTR lpString);
// LPSTR __stdcall lstrcpyA(LPSTR lpString1, LPCSTR lpString2);
// int _wsprintfA(LPSTR, LPCSTR, ...);
// void __cdecl _splitpath(const char *FullPath, char *Drive, char *Dir, char *Filename, char *Ext);
// DWORD __stdcall GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// unsigned int __stdcall rRegGetDWord(HKEY, const char *, const char *, unsigned int); idb
// int __stdcall rRegSetDWord(HKEY, const char *, const char *, unsigned int); idb


//----- (00000000) --------------------------------------------------------
LPSTR __stdcall lstrcatn(LPCSTR lpString, LPCSTR lpString2, int a3)
{
  int v3; // eax

  if ( !lpString || !lpString2 || a3 <= 0 )
    return 0;
  v3 = lstrlenA(lpString);
  return lstrcpynA((LPSTR)&lpString[v3], lpString2, a3 - v3);
}

//----- (00000040) --------------------------------------------------------
int __stdcall SetFullPath(LPSTR lpString1, int iMaxLength, LPCSTR lpString2, LPCSTR a4)
{
  if ( !lpString1 || !iMaxLength || !lpString2 || !a4 )
    return 0;
  lstrcpynA(lpString1, lpString2, iMaxLength);
  if ( *lpString1 )
  {
    if ( lpString1[lstrlenA(lpString1) - 1] != 92 )
      lstrcatn(lpString1, "\\", iMaxLength);
  }
  lstrcatn(lpString1, a4, iMaxLength);
  return 1;
}

//----- (000000B4) --------------------------------------------------------
// write access to const memory has been detected, the output may be wrong!
int __stdcall VfxGetAppPath(LPSTR lpString1, unsigned int *a2)
{
  unsigned int v2; // eax
  int result; // eax
  char Drive; // [esp+8h] [ebp-314h] BYREF
  __int16 v5; // [esp+9h] [ebp-313h]
  char v6; // [esp+Bh] [ebp-311h]
  CHAR String; // [esp+Ch] [ebp-310h] BYREF
  char v8[256]; // [esp+Dh] [ebp-30Fh] BYREF
  char Dir; // [esp+110h] [ebp-20Ch] BYREF
  char v10[256]; // [esp+111h] [ebp-20Bh] BYREF
  CHAR Filename; // [esp+214h] [ebp-108h] BYREF
  char v12[260]; // [esp+215h] [ebp-107h] BYREF

  Filename = 0;
  Dir = 0;
  memset(v12, 0, sizeof(v12));
  v5 = 0;
  String = 0;
  memset(v10, 0, sizeof(v10));
  memset(v8, 0, sizeof(v8));
  Drive = 0;
  v6 = 0;
  GetModuleFileNameA(0, &Filename, 0x104u);
  _splitpath(&Filename, &Drive, &Dir, 0, 0);
  _wsprintfA(&String, "%s%s", &Drive, &Dir);
  v2 = lstrlenA(&String);
  if ( a2 )
  {
    if ( *a2 < v2 )
    {
      result = 0;
    }
    else
    {
      lstrcpyA(lpString1, &String);
      result = 1;
    }
  }
  else
  {
    *(_DWORD *)lstrcatn = v2;
    result = 1;
  }
  return result;
}
// 171: write access to const memory at 0 has been detected

//----- (000001BC) --------------------------------------------------------
unsigned int __stdcall GetUpdateResult()
{
  unsigned int result; // eax

  result = rRegGetDWord(HKEY_CURRENT_USER, "SOFTWARE\\AHNLAB\\IOU\\HackShield", "HSUpdateResult", 0xFFFFFFFF);
  if ( result == -1 )
    result = 805306448;
  return result;
}

//----- (0000021C) --------------------------------------------------------
int __stdcall SetUpdateResult(unsigned int a1)
{
  return rRegSetDWord(HKEY_CURRENT_USER, "SOFTWARE\\AHNLAB\\IOU\\HackShield", "HSUpdateResult", a1) != 0 ? 0x30000050 : 0;
}

// nfuncs=13 queued=5 decompiled=5 lumina nreq=0 worse=0 better=0
// ALL OK, 5 function(s) have been successfully decompiled
