/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

unsigned int __stdcall _AhnHS_HSUpdate(LPCSTR lpCurrentDirectory, unsigned int); // idb
// DWORD __stdcall GetLastError();
// unsigned int __stdcall GetUpdateResult(); idb
// BOOL __stdcall SetEvent(HANDLE hEvent);
// HANDLE __stdcall OpenEventA(DWORD dwDesiredAccess, BOOL bInheritHandle, LPCSTR lpName);
// DWORD __stdcall WaitForSingleObject(HANDLE hHandle, DWORD dwMilliseconds);
// BOOL __stdcall CloseHandle(HANDLE hObject);
// BOOL __stdcall CreateProcessA(LPCSTR lpApplicationName, LPSTR lpCommandLine, LPSECURITY_ATTRIBUTES lpProcessAttributes, LPSECURITY_ATTRIBUTES lpThreadAttributes, BOOL bInheritHandles, DWORD dwCreationFlags, LPVOID lpEnvironment, LPCSTR lpCurrentDirectory, LPSTARTUPINFOA lpStartupInfo, LPPROCESS_INFORMATION lpProcessInformation);
// int __cdecl _access(const char *FileName, int AccessMode);
// HANDLE __stdcall CreateEventA(LPSECURITY_ATTRIBUTES lpEventAttributes, BOOL bManualReset, BOOL bInitialState, LPCSTR lpName);
// int __stdcall SetFullPath(char *, int, const char *, const char *); idb


//----- (00000000) --------------------------------------------------------
unsigned int __stdcall _AhnHS_HSUpdate(LPCSTR lpCurrentDirectory, unsigned int a2)
{
  unsigned int v2; // ebp
  HANDLE v3; // esi
  void (__stdcall *v4)(HANDLE); // edi
  DWORD v5; // ebp
  HANDLE v6; // eax
  void *v7; // esi
  struct _PROCESS_INFORMATION ProcessInformation; // [esp+10h] [ebp-168h] BYREF
  struct _STARTUPINFOA StartupInfo; // [esp+20h] [ebp-158h] BYREF
  char FileName; // [esp+64h] [ebp-114h] BYREF
  char v12[272]; // [esp+65h] [ebp-113h] BYREF
  __int16 v13; // [esp+175h] [ebp-3h]
  char v14; // [esp+177h] [ebp-1h]

  FileName = 0;
  memset(v12, 0, sizeof(v12));
  v13 = 0;
  v14 = 0;
  v2 = -1;
  SetFullPath(&FileName, 276, lpCurrentDirectory, "HSUpdate.exe");
  v3 = CreateEventA(0, 0, 0, "HSUPDATE_EXIT");
  if ( !v3 )
    return GetLastError();
  if ( _access(&FileName, 0) == -1 )
    return GetLastError();
  StartupInfo.cb = 68;
  memset(&StartupInfo.lpReserved, 0, 0x40u);
  ProcessInformation.hProcess = 0;
  ProcessInformation.hThread = 0;
  ProcessInformation.dwProcessId = 0;
  ProcessInformation.dwThreadId = 0;
  if ( !CreateProcessA(0, &FileName, 0, 0, 1, 0, 0, lpCurrentDirectory, &StartupInfo, &ProcessInformation) )
    return GetLastError();
  v4 = (void (__stdcall *)(HANDLE))CloseHandle;
  CloseHandle(ProcessInformation.hProcess);
  v4(ProcessInformation.hThread);
  if ( a2 )
    v2 = a2;
  v5 = WaitForSingleObject(v3, v2);
  v4(v3);
  if ( v5 != 258 )
    return GetUpdateResult();
  v6 = OpenEventA(0x1F0003u, 0, "HSUPDATE_TIMEOUT");
  v7 = v6;
  if ( v6 )
  {
    SetEvent(v6);
    v4(v7);
  }
  return 805306512;
}

// nfuncs=11 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
