/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __cdecl MDinit(unsigned int *); // idb
void __cdecl MDcompress(unsigned int *, unsigned int *); // idb
void __cdecl MDfinish(unsigned int *, unsigned __int8 *, unsigned int, unsigned int); // idb
unsigned __int8 *__cdecl MDbinary(LPCSTR lpFileName); // idb
// BOOL __stdcall CloseHandle(HANDLE hObject);
// BOOL __stdcall ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);

//-------------------------------------------------------------------------
// Data declarations

int _hashcode__1__MDbinary__YAPAEPBD_Z_4PAEA[]; // weak
int dword_2574; // weak
int dword_2578; // weak
int dword_257C; // weak
int dword_2580; // weak


//----- (00000000) --------------------------------------------------------
void __cdecl MDinit(unsigned int *a1)
{
  *a1 = 1732584193;
  a1[1] = -271733879;
  a1[2] = -1732584194;
  a1[3] = 271733878;
  a1[4] = -1009589776;
}

//----- (00000030) --------------------------------------------------------
void __cdecl MDcompress(unsigned int *a1, unsigned int *a2)
{
  unsigned int v2; // ebp
  unsigned int v3; // esi
  unsigned int v5; // edi
  int v6; // edx
  unsigned int v7; // ecx
  unsigned int v8; // ebx
  unsigned int v9; // esi
  unsigned int v10; // ebp
  unsigned int v11; // ecx
  unsigned int v12; // edx
  unsigned int v13; // ecx
  unsigned int v14; // edx
  unsigned __int64 v15; // kr00_8
  unsigned int v16; // ecx
  unsigned __int64 v17; // kr08_8
  unsigned int v18; // esi
  unsigned int v19; // ecx
  unsigned int v20; // eax
  unsigned int v21; // edx
  unsigned int v22; // eax
  unsigned int v23; // esi
  unsigned int v24; // eax
  unsigned int v25; // ecx
  unsigned int v26; // eax
  unsigned int v27; // edx
  unsigned int v28; // eax
  unsigned int v29; // esi
  unsigned int v30; // eax
  unsigned int v31; // ecx
  unsigned int v32; // edx
  unsigned int v33; // edx
  unsigned int v34; // eax
  unsigned int v35; // esi
  unsigned int v36; // eax
  unsigned int v37; // ecx
  unsigned int v38; // eax
  unsigned int v39; // edx
  unsigned int v40; // esi
  unsigned int v41; // esi
  unsigned int v42; // eax
  unsigned int v43; // ecx
  unsigned int v44; // eax
  unsigned int v45; // edx
  unsigned int v46; // eax
  unsigned int v47; // esi
  unsigned int v48; // eax
  unsigned __int64 v49; // kr10_8
  unsigned int v50; // ecx
  unsigned int v51; // edx
  unsigned int v52; // esi
  unsigned int v53; // eax
  unsigned int v54; // ecx
  unsigned int v55; // ecx
  unsigned int v56; // esi
  unsigned int v57; // edx
  unsigned int v58; // esi
  unsigned int v59; // eax
  unsigned int v60; // esi
  unsigned int v61; // ecx
  unsigned int v62; // esi
  unsigned int v63; // edx
  unsigned int v64; // esi
  unsigned int v65; // eax
  unsigned int v66; // esi
  unsigned int v67; // ecx
  unsigned int v68; // esi
  unsigned int v69; // edx
  unsigned int v70; // esi
  unsigned int v71; // eax
  unsigned int v72; // esi
  unsigned int v73; // ecx
  unsigned int v74; // esi
  unsigned int v75; // edx
  unsigned int v76; // esi
  unsigned int v77; // eax
  unsigned int v78; // esi
  unsigned int v79; // ecx
  int v80; // edx
  unsigned __int64 v81; // kr18_8
  unsigned int v82; // eax
  unsigned int v83; // esi
  int v84; // ecx
  unsigned int v85; // edx
  unsigned int v86; // ecx
  unsigned int v87; // edx
  unsigned int v88; // eax
  unsigned __int64 v89; // kr20_8
  int v90; // edx
  unsigned int v91; // esi
  unsigned int v92; // ecx
  unsigned int v93; // esi
  int v94; // eax
  unsigned int v95; // edx
  unsigned int v96; // eax
  unsigned int v97; // edx
  unsigned int v98; // ecx
  unsigned __int64 v99; // kr28_8
  int v100; // edx
  unsigned int v101; // esi
  unsigned int v102; // eax
  unsigned int v103; // esi
  int v104; // ecx
  unsigned int v105; // edx
  unsigned int v106; // ecx
  unsigned int v107; // edx
  unsigned int v108; // eax
  __int64 v109; // kr30_8
  int v110; // edx
  unsigned int v111; // ecx
  unsigned int v112; // ecx
  unsigned int v113; // esi
  unsigned int v114; // eax
  unsigned int v115; // edx
  unsigned int v116; // esi
  unsigned int v117; // ecx
  unsigned int v118; // esi
  unsigned int v119; // eax
  unsigned int v120; // edx
  unsigned int v121; // edx
  unsigned int v122; // esi
  unsigned int v123; // ecx
  unsigned int v124; // esi
  unsigned int v125; // eax
  unsigned int v126; // esi
  unsigned int v127; // edx
  unsigned int v128; // ecx
  unsigned int v129; // ecx
  unsigned int v130; // eax
  unsigned int v131; // eax
  unsigned int v132; // esi
  unsigned int v133; // edx
  unsigned int v134; // esi
  unsigned int v135; // ecx
  unsigned int v136; // esi
  unsigned int v137; // eax
  unsigned __int64 v138; // kr38_8
  unsigned int v139; // esi
  unsigned int v140; // esi
  unsigned int v141; // edx
  unsigned int v142; // eax
  unsigned __int64 v143; // kr40_8
  unsigned int v144; // ecx
  unsigned int v145; // edx
  unsigned int v146; // edx
  unsigned int v147; // esi
  unsigned int v148; // eax
  unsigned int v149; // esi
  unsigned int v150; // ecx
  unsigned int v151; // esi
  unsigned int v152; // edx
  unsigned int v153; // eax
  unsigned int v154; // eax
  unsigned int v155; // esi
  unsigned int v156; // ecx
  unsigned int v157; // esi
  unsigned int v158; // edx
  unsigned int v159; // esi
  unsigned int v160; // eax
  unsigned int v161; // esi
  unsigned int v162; // ecx
  unsigned int v163; // edx
  unsigned int v164; // edx
  unsigned int v165; // esi
  unsigned int v166; // eax
  unsigned int v167; // esi
  unsigned int v168; // ecx
  unsigned int v169; // esi
  unsigned int v170; // edx
  unsigned __int64 v171; // kr48_8
  unsigned int v172; // eax
  unsigned int v173; // ecx
  unsigned int v174; // eax
  unsigned __int64 v175; // kr50_8
  unsigned int v176; // edx
  unsigned int v177; // esi
  int v178; // ecx
  unsigned int v179; // ecx
  unsigned int v180; // eax
  int v181; // edx
  unsigned int v182; // ecx
  unsigned int v183; // esi
  int v184; // eax
  unsigned int v185; // edx
  unsigned int v186; // eax
  unsigned int v187; // edx
  unsigned int v188; // ecx
  unsigned __int64 v189; // kr58_8
  int v190; // edx
  unsigned int v191; // esi
  unsigned int v192; // eax
  unsigned int v193; // esi
  int v194; // ecx
  unsigned int v195; // edx
  unsigned int v196; // ecx
  unsigned int v197; // edx
  unsigned int v198; // eax
  unsigned __int64 v199; // kr60_8
  unsigned int v200; // edx
  unsigned int v201; // esi
  unsigned int v202; // ecx
  unsigned int v203; // esi
  unsigned int v204; // eax
  unsigned int v205; // edx
  unsigned int v206; // edx
  unsigned int v207; // esi
  unsigned int v208; // ecx
  unsigned int v209; // esi
  unsigned int v210; // eax
  unsigned int v211; // esi
  unsigned int v212; // edx
  unsigned int v213; // esi
  unsigned int v214; // ecx
  unsigned int v215; // esi
  unsigned int v216; // eax
  unsigned int v217; // esi
  unsigned int v218; // edx
  unsigned int v219; // esi
  unsigned int v220; // ecx
  unsigned int v221; // esi
  unsigned int v222; // eax
  unsigned __int64 v223; // kr68_8
  unsigned int v224; // edx
  unsigned int v225; // esi
  unsigned int v226; // ecx
  unsigned int v227; // eax
  unsigned int v228; // ecx
  unsigned int v229; // edx
  unsigned int v230; // esi
  unsigned int v231; // eax
  unsigned int v232; // ecx
  unsigned int v233; // eax
  unsigned int v234; // edx
  unsigned int v235; // esi
  unsigned int v236; // esi
  unsigned int v237; // eax
  unsigned int v238; // ecx
  unsigned int v239; // eax
  unsigned int v240; // edx
  unsigned int v241; // eax
  unsigned int v242; // esi
  unsigned int v243; // ecx
  unsigned int v244; // ecx
  unsigned int v245; // eax
  unsigned int v246; // edx
  unsigned int v247; // eax
  unsigned int v248; // esi
  unsigned int v249; // eax
  unsigned int v250; // ecx
  unsigned int v251; // edx
  unsigned int v252; // edx
  unsigned int v253; // eax
  unsigned int v254; // esi
  unsigned int v255; // eax
  unsigned int v256; // ecx
  unsigned int v257; // eax
  unsigned int v258; // edx
  __int64 v259; // kr70_8
  unsigned int v260; // ecx
  unsigned __int64 v261; // kr78_8
  unsigned int v262; // eax
  unsigned int v263; // edx
  int v264; // esi
  unsigned int v265; // ecx
  __int64 v266; // kr80_8
  int v267; // ebx
  unsigned int v268; // eax
  unsigned int v269; // edx
  unsigned __int64 v270; // kr88_8
  unsigned int v271; // ecx
  int v272; // esi
  unsigned int v273; // eax
  int v274; // ebx
  unsigned int v275; // edx
  unsigned int v276; // ecx
  __int64 v277; // kr90_8
  int v278; // esi
  unsigned int v279; // eax
  unsigned int v280; // edx
  int v281; // edi
  int v282; // ebx
  unsigned int v283; // ecx
  unsigned int v284; // ebp
  unsigned int v285; // edi
  unsigned int v286; // edx
  unsigned int v287; // ecx
  int v288; // edi
  unsigned int v289; // [esp+10h] [ebp-58h]
  int v290; // [esp+10h] [ebp-58h]
  unsigned int v291; // [esp+10h] [ebp-58h]
  int v292; // [esp+10h] [ebp-58h]
  int v293; // [esp+10h] [ebp-58h]
  int v294; // [esp+10h] [ebp-58h]
  int v295; // [esp+10h] [ebp-58h]
  int v296; // [esp+10h] [ebp-58h]
  int v297; // [esp+10h] [ebp-58h]
  int v298; // [esp+10h] [ebp-58h]
  int v299; // [esp+10h] [ebp-58h]
  unsigned int v300; // [esp+10h] [ebp-58h]
  int v301; // [esp+10h] [ebp-58h]
  unsigned int v302; // [esp+10h] [ebp-58h]
  int v303; // [esp+10h] [ebp-58h]
  unsigned int v304; // [esp+10h] [ebp-58h]
  int v305; // [esp+10h] [ebp-58h]
  unsigned int v306; // [esp+10h] [ebp-58h]
  int v307; // [esp+10h] [ebp-58h]
  int v308; // [esp+10h] [ebp-58h]
  int v309; // [esp+10h] [ebp-58h]
  unsigned int v310; // [esp+10h] [ebp-58h]
  unsigned int v311; // [esp+14h] [ebp-54h]
  unsigned int v312; // [esp+14h] [ebp-54h]
  int v313; // [esp+14h] [ebp-54h]
  int v314; // [esp+14h] [ebp-54h]
  unsigned int v315; // [esp+14h] [ebp-54h]
  int v316; // [esp+14h] [ebp-54h]
  int v317; // [esp+14h] [ebp-54h]
  int v318; // [esp+14h] [ebp-54h]
  int v319; // [esp+14h] [ebp-54h]
  int v320; // [esp+14h] [ebp-54h]
  int v321; // [esp+14h] [ebp-54h]
  int v322; // [esp+14h] [ebp-54h]
  int v323; // [esp+14h] [ebp-54h]
  int v324; // [esp+14h] [ebp-54h]
  int v325; // [esp+14h] [ebp-54h]
  int v326; // [esp+14h] [ebp-54h]
  int v327; // [esp+14h] [ebp-54h]
  int v328; // [esp+14h] [ebp-54h]
  int v329; // [esp+14h] [ebp-54h]
  unsigned int v330; // [esp+18h] [ebp-50h]
  int v331; // [esp+18h] [ebp-50h]
  int v332; // [esp+18h] [ebp-50h]
  unsigned int v333; // [esp+18h] [ebp-50h]
  int v334; // [esp+18h] [ebp-50h]
  int v335; // [esp+18h] [ebp-50h]
  int v336; // [esp+18h] [ebp-50h]
  int v337; // [esp+18h] [ebp-50h]
  int v338; // [esp+18h] [ebp-50h]
  int v339; // [esp+18h] [ebp-50h]
  int v340; // [esp+18h] [ebp-50h]
  int v341; // [esp+18h] [ebp-50h]
  int v342; // [esp+18h] [ebp-50h]
  int v343; // [esp+18h] [ebp-50h]
  int v344; // [esp+18h] [ebp-50h]
  int v345; // [esp+18h] [ebp-50h]
  int v346; // [esp+18h] [ebp-50h]
  unsigned int v347; // [esp+18h] [ebp-50h]
  int v348; // [esp+1Ch] [ebp-4Ch]
  int v349; // [esp+1Ch] [ebp-4Ch]
  int v350; // [esp+1Ch] [ebp-4Ch]
  int v351; // [esp+1Ch] [ebp-4Ch]
  int v352; // [esp+1Ch] [ebp-4Ch]
  unsigned int v353; // [esp+1Ch] [ebp-4Ch]
  int v354; // [esp+1Ch] [ebp-4Ch]
  int v355; // [esp+1Ch] [ebp-4Ch]
  int v356; // [esp+1Ch] [ebp-4Ch]
  int v357; // [esp+1Ch] [ebp-4Ch]
  int v358; // [esp+1Ch] [ebp-4Ch]
  int v359; // [esp+1Ch] [ebp-4Ch]
  int v360; // [esp+1Ch] [ebp-4Ch]
  int v361; // [esp+1Ch] [ebp-4Ch]
  int v362; // [esp+1Ch] [ebp-4Ch]
  int v363; // [esp+1Ch] [ebp-4Ch]
  int v364; // [esp+20h] [ebp-48h]
  int v365; // [esp+20h] [ebp-48h]
  int v366; // [esp+20h] [ebp-48h]
  int v367; // [esp+20h] [ebp-48h]
  unsigned int v368; // [esp+20h] [ebp-48h]
  int v369; // [esp+20h] [ebp-48h]
  unsigned int v370; // [esp+20h] [ebp-48h]
  int v371; // [esp+20h] [ebp-48h]
  int v372; // [esp+20h] [ebp-48h]
  int v373; // [esp+20h] [ebp-48h]
  int v374; // [esp+20h] [ebp-48h]
  int v375; // [esp+20h] [ebp-48h]
  int v376; // [esp+20h] [ebp-48h]
  int v377; // [esp+20h] [ebp-48h]
  int v378; // [esp+20h] [ebp-48h]
  int v379; // [esp+20h] [ebp-48h]
  unsigned int v380; // [esp+24h] [ebp-44h]
  int v381; // [esp+24h] [ebp-44h]
  int v382; // [esp+24h] [ebp-44h]
  int v383; // [esp+24h] [ebp-44h]
  unsigned int v384; // [esp+24h] [ebp-44h]
  int v385; // [esp+24h] [ebp-44h]
  int v386; // [esp+24h] [ebp-44h]
  int v387; // [esp+24h] [ebp-44h]
  int v388; // [esp+24h] [ebp-44h]
  int v389; // [esp+24h] [ebp-44h]
  int v390; // [esp+24h] [ebp-44h]
  int v391; // [esp+24h] [ebp-44h]
  int v392; // [esp+24h] [ebp-44h]
  int v393; // [esp+24h] [ebp-44h]
  int v394; // [esp+24h] [ebp-44h]
  int v395; // [esp+24h] [ebp-44h]
  int v396; // [esp+24h] [ebp-44h]
  unsigned int v397; // [esp+28h] [ebp-40h]
  int v398; // [esp+28h] [ebp-40h]
  int v399; // [esp+28h] [ebp-40h]
  int v400; // [esp+28h] [ebp-40h]
  int v401; // [esp+28h] [ebp-40h]
  int v402; // [esp+28h] [ebp-40h]
  int v403; // [esp+28h] [ebp-40h]
  int v404; // [esp+28h] [ebp-40h]
  int v405; // [esp+28h] [ebp-40h]
  int v406; // [esp+28h] [ebp-40h]
  int v407; // [esp+28h] [ebp-40h]
  int v408; // [esp+28h] [ebp-40h]
  int v409; // [esp+28h] [ebp-40h]
  int v410; // [esp+28h] [ebp-40h]
  int v411; // [esp+28h] [ebp-40h]
  int v412; // [esp+28h] [ebp-40h]
  int v413; // [esp+2Ch] [ebp-3Ch]
  unsigned int v414; // [esp+2Ch] [ebp-3Ch]
  int v415; // [esp+2Ch] [ebp-3Ch]
  int v416; // [esp+2Ch] [ebp-3Ch]
  int v417; // [esp+2Ch] [ebp-3Ch]
  int v418; // [esp+2Ch] [ebp-3Ch]
  int v419; // [esp+2Ch] [ebp-3Ch]
  int v420; // [esp+2Ch] [ebp-3Ch]
  int v421; // [esp+2Ch] [ebp-3Ch]
  int v422; // [esp+2Ch] [ebp-3Ch]
  int v423; // [esp+2Ch] [ebp-3Ch]
  int v424; // [esp+2Ch] [ebp-3Ch]
  int v425; // [esp+2Ch] [ebp-3Ch]
  unsigned int v426; // [esp+30h] [ebp-38h]
  int v427; // [esp+30h] [ebp-38h]
  int v428; // [esp+30h] [ebp-38h]
  int v429; // [esp+30h] [ebp-38h]
  int v430; // [esp+30h] [ebp-38h]
  unsigned int v431; // [esp+30h] [ebp-38h]
  int v432; // [esp+30h] [ebp-38h]
  int v433; // [esp+30h] [ebp-38h]
  int v434; // [esp+30h] [ebp-38h]
  int v435; // [esp+30h] [ebp-38h]
  int v436; // [esp+30h] [ebp-38h]
  int v437; // [esp+30h] [ebp-38h]
  int v438; // [esp+30h] [ebp-38h]
  int v439; // [esp+30h] [ebp-38h]
  unsigned int v440; // [esp+34h] [ebp-34h]
  unsigned int v441; // [esp+38h] [ebp-30h]
  unsigned int v442; // [esp+3Ch] [ebp-2Ch]
  unsigned int v443; // [esp+40h] [ebp-28h]
  unsigned int v444; // [esp+44h] [ebp-24h]
  unsigned int v445; // [esp+48h] [ebp-20h]
  unsigned int v446; // [esp+4Ch] [ebp-1Ch]
  unsigned int v447; // [esp+50h] [ebp-18h]
  unsigned int v448; // [esp+54h] [ebp-14h]
  unsigned int v449; // [esp+58h] [ebp-10h]
  unsigned int v450; // [esp+5Ch] [ebp-Ch]
  unsigned int v451; // [esp+60h] [ebp-8h]
  unsigned int v452; // [esp+64h] [ebp-4h]
  unsigned int *v453; // [esp+70h] [ebp+8h]
  int v454; // [esp+70h] [ebp+8h]
  unsigned int *v455; // [esp+70h] [ebp+8h]
  unsigned int *v456; // [esp+70h] [ebp+8h]
  int v457; // [esp+70h] [ebp+8h]
  int v458; // [esp+70h] [ebp+8h]
  int v459; // [esp+70h] [ebp+8h]
  int v460; // [esp+70h] [ebp+8h]
  int v461; // [esp+70h] [ebp+8h]
  int v462; // [esp+70h] [ebp+8h]
  int v463; // [esp+70h] [ebp+8h]
  int v464; // [esp+70h] [ebp+8h]
  unsigned int *v465; // [esp+70h] [ebp+8h]
  int v466; // [esp+70h] [ebp+8h]
  unsigned int *v467; // [esp+70h] [ebp+8h]
  int v468; // [esp+70h] [ebp+8h]
  unsigned int *v469; // [esp+70h] [ebp+8h]
  int v470; // [esp+70h] [ebp+8h]
  int v471; // [esp+70h] [ebp+8h]
  int v472; // [esp+70h] [ebp+8h]
  unsigned int v473; // [esp+70h] [ebp+8h]

  v2 = a1[1];
  v3 = a1[2];
  v289 = a1[3];
  v5 = *a2;
  v311 = a1[4];
  v6 = (v3 << 10) | (v3 >> 22);
  v7 = v311 + (((*a1 + v5 + (v2 ^ v3 ^ v289)) << 11) | ((*a1 + v5 + (v2 ^ v3 ^ v289)) >> 21));
  v8 = a2[1];
  v312 = v289 + (((v8 + (v7 ^ v2 ^ v6) + v311) << 14) | ((v8 + (v7 ^ v2 ^ v6) + v311) >> 18));
  v447 = a2[2];
  v453 = (unsigned int *)((v2 << 10) | ((unsigned __int64)v2 >> 22));
  v9 = v6
     + (((v447 + (v7 ^ (unsigned int)v453 ^ v312) + v289) << 15) | ((v447 + (v7 ^ (unsigned int)v453 ^ v312) + v289) >> 17));
  v413 = (v7 << 10) | (v7 >> 22);
  v10 = a2[3];
  v330 = (unsigned int)v453 + (((v10 + (v413 ^ v9 ^ v312) + v6) << 12) | ((v10 + (v413 ^ v9 ^ v312) + v6) >> 20));
  v313 = (v312 << 10) | ((unsigned __int64)v312 >> 22);
  v442 = a2[4];
  v11 = v413
      + ((32 * ((_DWORD)v453 + v442 + (v330 ^ v9 ^ v313))) | (((unsigned int)v453 + v442 + (v330 ^ v9 ^ v313)) >> 27));
  v443 = a2[5];
  v290 = (v9 << 10) | (v9 >> 22);
  v414 = v313 + (((v443 + (v11 ^ v330 ^ v290) + v413) << 8) | ((v443 + (v11 ^ v330 ^ v290) + v413) >> 24));
  v331 = (v330 << 10) | ((unsigned __int64)v330 >> 22);
  v446 = a2[6];
  v12 = v290 + (((v446 + (v414 ^ v11 ^ v331) + v313) << 7) | ((v446 + (v414 ^ v11 ^ v331) + v313) >> 25));
  v445 = a2[7];
  v454 = (v11 << 10) | (v11 >> 22);
  v291 = v331 + (((v445 + (v414 ^ v454 ^ v12) + v290) << 9) | ((v445 + (v414 ^ v454 ^ v12) + v290) >> 23));
  v415 = (v414 << 10) | ((unsigned __int64)v414 >> 22);
  v444 = a2[8];
  v13 = v454 + (((v444 + (v415 ^ v291 ^ v12) + v331) << 11) | ((v444 + (v415 ^ v291 ^ v12) + v331) >> 21));
  v450 = a2[9];
  v314 = (v12 << 10) | (v12 >> 22);
  v455 = (unsigned int *)(v415
                        + (((v450 + (v13 ^ v291 ^ v314) + v454) << 13) | ((v450 + (v13 ^ v291 ^ v314) + v454) >> 19)));
  v292 = (v291 << 10) | ((unsigned __int64)v291 >> 22);
  v441 = a2[10];
  v14 = v314
      + (((v441 + ((unsigned int)v455 ^ v13 ^ v292) + v415) << 14) | ((v441 + ((unsigned int)v455 ^ v13 ^ v292) + v415) >> 18));
  v332 = (v13 << 10) | (v13 >> 22);
  v451 = a2[11];
  v315 = v292
       + (((v451 + (v14 ^ (unsigned int)v455 ^ v332) + v314) << 15) | ((v451 + (v14 ^ (unsigned int)v455 ^ v332) + v314) >> 17));
  v440 = a2[12];
  v456 = (unsigned int *)(((_DWORD)v455 << 10) | ((unsigned __int64)(unsigned int)v455 >> 22));
  v15 = (unsigned __int64)(v440 + (v14 ^ (unsigned int)v456 ^ v315) + v292) << 6;
  v16 = v332 + (v15 | HIDWORD(v15));
  v448 = a2[13];
  v416 = (v14 << 10) | (v14 >> 22);
  v333 = (unsigned int)v456 + (((v448 + (v416 ^ v16 ^ v315) + v332) << 7) | ((v448 + (v416 ^ v16 ^ v315) + v332) >> 25));
  v449 = a2[14];
  v316 = (v315 << 10) | ((unsigned __int64)v315 >> 22);
  v17 = (unsigned __int64)((unsigned int)v456 + v449 + (v333 ^ v16 ^ v316)) << 9;
  v18 = v416 + (v17 | HIDWORD(v17));
  v452 = a2[15];
  v293 = (v16 << 10) | (v16 >> 22);
  v19 = v316 + (((v452 + (v18 ^ v333 ^ v293) + v416) << 8) | ((v452 + (v18 ^ v333 ^ v293) + v416) >> 24));
  v334 = (v333 << 10) | ((unsigned __int64)v333 >> 22);
  v20 = v316 + v445 + (v19 & v18 | v334 & ~v19) + 1518500249;
  v21 = v293 + ((v20 << 7) | (v20 >> 25));
  v457 = (v18 << 10) | (v18 >> 22);
  v22 = v293 + v442 + (v19 & v21 | v457 & ~v21) + 1518500249;
  v23 = v334 + ((v22 << 6) | (v22 >> 26));
  v417 = (v19 << 10) | (v19 >> 22);
  v24 = v334 + v448 + (v23 & v21 | v417 & ~v23) + 1518500249;
  v25 = v457 + ((v24 << 8) | HIBYTE(v24));
  v317 = (v21 << 10) | (v21 >> 22);
  v26 = v457 + v8 + (v25 & v23 | v317 & ~v25) + 1518500249;
  v27 = v417 + ((v26 << 13) | (v26 >> 19));
  v294 = (v23 << 10) | (v23 >> 22);
  v28 = v417 + v441 + (v27 & v25 | v294 & ~v27) + 1518500249;
  v29 = v317 + ((v28 << 11) | (v28 >> 21));
  v335 = (v25 << 10) | (v25 >> 22);
  v30 = v317 + v446 + (v29 & v27 | v335 & ~v29) + 1518500249;
  v31 = v294 + ((v30 << 9) | (v30 >> 23));
  v458 = (v27 << 10) | (v27 >> 22);
  v32 = v294 + v452 + (v29 & v31 | v458 & ~v31) + 1518500249;
  v33 = v335 + ((v32 << 7) | (v32 >> 25));
  v418 = (v29 << 10) | (v29 >> 22);
  v34 = v335 + v10 + (v33 & v31 | v418 & ~v33) + 1518500249;
  v35 = v458 + ((v34 << 15) | (v34 >> 17));
  v318 = (v31 << 10) | (v31 >> 22);
  v36 = v458 + v440 + (v35 & v33 | v318 & ~v35) + 1518500249;
  v37 = v418 + ((v36 << 7) | (v36 >> 25));
  v295 = (v33 << 10) | (v33 >> 22);
  v38 = v418 + v5 + (v37 & v35 | v295 & ~v37) + 1518500249;
  v39 = v318 + ((v38 << 12) | (v38 >> 20));
  v336 = (v35 << 10) | (v35 >> 22);
  v40 = v318 + v450 + (v39 & v37 | v336 & ~v39) + 1518500249;
  v41 = v295 + ((v40 << 15) | (v40 >> 17));
  v459 = (v37 << 10) | (v37 >> 22);
  v42 = v295 + v443 + (v39 & v41 | v459 & ~v41) + 1518500249;
  v43 = v336 + ((v42 << 9) | (v42 >> 23));
  v419 = (v39 << 10) | (v39 >> 22);
  v44 = v336 + v447 + (v43 & v41 | v419 & ~v43) + 1518500249;
  v45 = v459 + ((v44 << 11) | (v44 >> 21));
  v319 = (v41 << 10) | (v41 >> 22);
  v46 = v459 + v449 + (v45 & v43 | v319 & ~v45) + 1518500249;
  v47 = v419 + ((v46 << 7) | (v46 >> 25));
  v296 = (v43 << 10) | (v43 >> 22);
  v48 = v319
      + (((v419 + v451 + (v47 & v45 | v296 & ~v47) + 1518500249) << 13) | ((v419
                                                                          + v451
                                                                          + (v47 & v45 | v296 & ~v47)
                                                                          + 1518500249) >> 19));
  v337 = (v45 << 10) | (v45 >> 22);
  v49 = (unsigned __int64)(v319 + v444 + (v48 & v47 | v337 & ~v48) + 1518500249) << 12;
  v50 = v296 + (v49 | HIDWORD(v49));
  v460 = (v47 << 10) | (v47 >> 22);
  v51 = v337
      + (((v296 + v10 + (v460 ^ (v50 | ~v48)) + 1859775393) << 11) | ((v296 + v10 + (v460 ^ (v50 | ~v48)) + 1859775393) >> 21));
  v420 = (v48 << 10) | (v48 >> 22);
  v52 = v337 + v441 + (v420 ^ (v51 | ~v50)) + 1859775393;
  v53 = v460 + ((v52 << 13) | (v52 >> 19));
  v320 = (v50 << 10) | (v50 >> 22);
  v54 = v460 + v449 + (v320 ^ (v53 | ~v51)) + 1859775393;
  v55 = v420 + ((v54 << 6) | (v54 >> 26));
  v297 = (v51 << 10) | (v51 >> 22);
  v56 = v420 + v442 + (v297 ^ (v55 | ~v53)) + 1859775393;
  v57 = v320 + ((v56 << 7) | (v56 >> 25));
  v338 = (v53 << 10) | (v53 >> 22);
  v58 = v320 + v450 + (v338 ^ (v57 | ~v55)) + 1859775393;
  v59 = v297 + ((v58 << 14) | (v58 >> 18));
  v461 = (v55 << 10) | (v55 >> 22);
  v60 = v297 + v452 + (v461 ^ (v59 | ~v57)) + 1859775393;
  v61 = v338 + ((v60 << 9) | (v60 >> 23));
  v421 = (v57 << 10) | (v57 >> 22);
  v62 = v338 + v444 + (v421 ^ (v61 | ~v59)) + 1859775393;
  v63 = v461 + ((v62 << 13) | (v62 >> 19));
  v321 = (v59 << 10) | (v59 >> 22);
  v64 = v461 + v8 + (v321 ^ (v63 | ~v61)) + 1859775393;
  v65 = v421 + ((v64 << 15) | (v64 >> 17));
  v298 = (v61 << 10) | (v61 >> 22);
  v66 = v421 + v447 + (v298 ^ (v65 | ~v63)) + 1859775393;
  v67 = v321 + ((v66 << 14) | (v66 >> 18));
  v339 = (v63 << 10) | (v63 >> 22);
  v68 = v321 + v445 + (v339 ^ (v67 | ~v65)) + 1859775393;
  v69 = v298 + ((v68 << 8) | HIBYTE(v68));
  v462 = (v65 << 10) | (v65 >> 22);
  v70 = v298 + v5 + (v462 ^ (v69 | ~v67)) + 1859775393;
  v71 = v339 + ((v70 << 13) | (v70 >> 19));
  v422 = (v67 << 10) | (v67 >> 22);
  v72 = v339 + v446 + (v422 ^ (v71 | ~v69)) + 1859775393;
  v73 = v462 + ((v72 << 6) | (v72 >> 26));
  v322 = (v69 << 10) | (v69 >> 22);
  v74 = v462 + v448 + (v322 ^ (v73 | ~v71)) + 1859775393;
  v75 = v422 + ((32 * v74) | (v74 >> 27));
  v299 = (v71 << 10) | (v71 >> 22);
  v76 = v422 + v451 + (v299 ^ (v75 | ~v73)) + 1859775393;
  v77 = v322 + ((v76 << 12) | (v76 >> 20));
  v340 = (v73 << 10) | (v73 >> 22);
  v78 = v322 + v443 + (v340 ^ (v77 | ~v75)) + 1859775393;
  v79 = v299 + ((v78 << 7) | (v78 >> 25));
  v463 = (v75 << 10) | (v75 >> 22);
  v80 = (v77 << 10) | (v77 >> 22);
  v300 = v340
       + ((32 * (v299 + v440 + (v463 ^ (v79 | ~v77)) + 1859775393)) | ((v299 + v440 + (v463 ^ (v79 | ~v77)) + 1859775393) >> 27));
  v81 = (unsigned __int64)(v340 + v8 + (v80 & v300 | v79 & ~v80) - 1894007588) << 11;
  v82 = v463 + (v81 | HIDWORD(v81));
  v323 = (v79 << 10) | (v79 >> 22);
  v83 = v463 + v450 + (v82 & v323 | v300 & ~v323) - 1894007588;
  v84 = (v83 << 12) | (v83 >> 20);
  v464 = v80 + v84;
  v301 = (v300 << 10) | ((unsigned __int64)v300 >> 22);
  v85 = v80 + v451 + ((v80 + v84) & v301 | v82 & ~v301) - 1894007588;
  v86 = v323 + ((v85 << 14) | (v85 >> 18));
  v341 = (v82 << 10) | (v82 >> 22);
  v87 = v323 + v441 + (v86 & v341 | v464 & ~v341) - 1894007588;
  v88 = v301 + ((v87 << 15) | (v87 >> 17));
  v465 = (unsigned int *)((v464 << 10) | ((unsigned __int64)(unsigned int)v464 >> 22));
  v89 = (unsigned __int64)(v301 + v5 + ((unsigned int)v465 & v88 | v86 & ~(unsigned int)v465) - 1894007588) << 14;
  v90 = (v86 << 10) | (v86 >> 22);
  v302 = v341 + (v89 | HIDWORD(v89));
  v91 = v341 + v444 + (v90 & v302 | v88 & ~v90) - 1894007588;
  v92 = (unsigned int)v465 + ((v91 << 15) | (v91 >> 17));
  v324 = (v88 << 10) | (v88 >> 22);
  v93 = (unsigned int)v465 + v440 + (v92 & v324 | v302 & ~v324) - 1894007588;
  v94 = (v93 << 9) | (v93 >> 23);
  v466 = v90 + v94;
  v303 = (v302 << 10) | ((unsigned __int64)v302 >> 22);
  v95 = v90 + v442 + ((v90 + v94) & v303 | v92 & ~v303) - 1894007588;
  v96 = v324 + ((v95 << 8) | HIBYTE(v95));
  v342 = (v92 << 10) | (v92 >> 22);
  v97 = v324 + v448 + (v96 & v342 | v466 & ~v342) - 1894007588;
  v98 = v303 + ((v97 << 9) | (v97 >> 23));
  v467 = (unsigned int *)((v466 << 10) | ((unsigned __int64)(unsigned int)v466 >> 22));
  v99 = (unsigned __int64)(v303 + v10 + ((unsigned int)v467 & v98 | v96 & ~(unsigned int)v467) - 1894007588) << 14;
  v100 = (v96 << 10) | (v96 >> 22);
  v304 = v342 + (v99 | HIDWORD(v99));
  v101 = v342 + v445 + (v100 & v304 | v98 & ~v100) - 1894007588;
  v102 = (unsigned int)v467 + ((32 * v101) | (v101 >> 27));
  v325 = (v98 << 10) | (v98 >> 22);
  v103 = (unsigned int)v467 + v452 + (v102 & v325 | v304 & ~v325) - 1894007588;
  v104 = (v103 << 6) | (v103 >> 26);
  v468 = v100 + v104;
  v305 = (v304 << 10) | ((unsigned __int64)v304 >> 22);
  v105 = v100 + v449 + ((v100 + v104) & v305 | v102 & ~v305) - 1894007588;
  v106 = v325 + ((v105 << 8) | HIBYTE(v105));
  v343 = (v102 << 10) | (v102 >> 22);
  v107 = v325 + v443 + (v106 & v343 | v468 & ~v343) - 1894007588;
  v108 = v305 + ((v107 << 6) | (v107 >> 26));
  v469 = (unsigned int *)((v468 << 10) | ((unsigned __int64)(unsigned int)v468 >> 22));
  v109 = 32i64 * (v305 + v446 + ((unsigned int)v469 & v108 | v106 & ~(unsigned int)v469) - 1894007588);
  v110 = (v106 << 10) | (v106 >> 22);
  v306 = v343 + (v109 | HIDWORD(v109));
  v111 = v343 + v447 + (v110 & v306 | v108 & ~v110) - 1894007588;
  v112 = (unsigned int)v469 + ((v111 << 12) | (v111 >> 20));
  v326 = (v108 << 10) | (v108 >> 22);
  v113 = (unsigned int)v469 + v442 + (v112 ^ (v306 | ~v326)) - 1454113458;
  v114 = v110 + ((v113 << 9) | (v113 >> 23));
  v307 = (v306 << 10) | ((unsigned __int64)v306 >> 22);
  v115 = v326
       + (((v110 + v5 + (v114 ^ (v112 | ~v307)) - 1454113458) << 15) | ((v110 + v5 + (v114 ^ (v112 | ~v307)) - 1454113458) >> 17));
  v344 = (v112 << 10) | (v112 >> 22);
  v116 = v326 + v443 + (v115 ^ (v114 | ~v344)) - 1454113458;
  v117 = v307 + ((32 * v116) | (v116 >> 27));
  v470 = (v114 << 10) | (v114 >> 22);
  v118 = v307 + v450 + (v117 ^ (v115 | ~v470)) - 1454113458;
  v119 = v344 + ((v118 << 11) | (v118 >> 21));
  v423 = (v115 << 10) | (v115 >> 22);
  v120 = v344 + v445 + (v119 ^ (v117 | ~v423)) - 1454113458;
  v121 = v470 + ((v120 << 6) | (v120 >> 26));
  v327 = (v117 << 10) | (v117 >> 22);
  v122 = v470 + v440 + (v121 ^ (v119 | ~v327)) - 1454113458;
  v123 = v423 + ((v122 << 8) | HIBYTE(v122));
  v308 = (v119 << 10) | (v119 >> 22);
  v124 = v423 + v447 + (v123 ^ (v121 | ~v308)) - 1454113458;
  v125 = v327 + ((v124 << 13) | (v124 >> 19));
  v345 = (v121 << 10) | (v121 >> 22);
  v126 = v327 + v441 + (v125 ^ (v123 | ~v345)) - 1454113458;
  v127 = v308 + ((v126 << 12) | (v126 >> 20));
  v471 = (v123 << 10) | (v123 >> 22);
  v128 = v308 + v449 + (v127 ^ (v125 | ~v471)) - 1454113458;
  v129 = v345 + ((32 * v128) | (v128 >> 27));
  v424 = (v125 << 10) | (v125 >> 22);
  v130 = v345 + v8 + (v129 ^ (v127 | ~v424)) - 1454113458;
  v131 = v471 + ((v130 << 12) | (v130 >> 20));
  v328 = (v127 << 10) | (v127 >> 22);
  v132 = v471 + v10 + (v131 ^ (v129 | ~v328)) - 1454113458;
  v133 = v424 + ((v132 << 13) | (v132 >> 19));
  v309 = (v129 << 10) | (v129 >> 22);
  v134 = v424 + v444 + (v133 ^ (v131 | ~v309)) - 1454113458;
  v135 = v328 + ((v134 << 14) | (v134 >> 18));
  v346 = (v131 << 10) | (v131 >> 22);
  v136 = v328 + v451 + (v135 ^ (v133 | ~v346)) - 1454113458;
  v137 = v309 + ((v136 << 11) | (v136 >> 21));
  v472 = (v133 << 10) | (v133 >> 22);
  v138 = (unsigned __int64)(v309 + v446 + (v137 ^ (v135 | ~v472)) - 1454113458) << 8;
  v425 = (v135 << 10) | (v135 >> 22);
  v310 = v346 + (v138 | HIDWORD(v138));
  v139 = v346 + v452 + (v310 ^ (v137 | ~v425)) - 1454113458;
  v347 = v472 + ((32 * v139) | (v139 >> 27));
  v329 = (v137 << 10) | (v137 >> 22);
  v140 = a1[1];
  v473 = v472 + v448 + (v347 ^ (v310 | ~v329)) - 1454113458;
  v426 = a1[3];
  v397 = a1[2];
  v141 = v443 + (v140 ^ (v397 | ~v426)) + *a1 + 1352829926;
  v380 = a1[4];
  v142 = v380 + ((v141 << 8) | HIBYTE(v141));
  v398 = (v397 << 10) | ((unsigned __int64)v397 >> 22);
  v143 = (unsigned __int64)(v380 + v449 + (v142 ^ (v140 | ~v398)) + 1352829926) << 9;
  v144 = v426 + (v143 | HIDWORD(v143));
  v348 = (v140 << 10) | (v140 >> 22);
  v145 = v426 + v445 + (v144 ^ (v142 | ~v348)) + 1352829926;
  v146 = v398 + ((v145 << 9) | (v145 >> 23));
  v427 = (v142 << 10) | (v142 >> 22);
  v147 = v398 + v5 + (v146 ^ (v144 | ~v427)) + 1352829926;
  v148 = v348 + ((v147 << 11) | (v147 >> 21));
  v381 = (v144 << 10) | (v144 >> 22);
  v149 = v348 + v450 + (v148 ^ (v146 | ~v381)) + 1352829926;
  v150 = v427 + ((v149 << 13) | (v149 >> 19));
  v364 = (v146 << 10) | (v146 >> 22);
  v151 = v427 + v447 + (v150 ^ (v148 | ~v364)) + 1352829926;
  v152 = v381 + ((v151 << 15) | (v151 >> 17));
  v399 = (v148 << 10) | (v148 >> 22);
  v153 = v381 + v451 + (v152 ^ (v150 | ~v399)) + 1352829926;
  v154 = v364 + ((v153 << 15) | (v153 >> 17));
  v349 = (v150 << 10) | (v150 >> 22);
  v155 = v364 + v442 + (v154 ^ (v152 | ~v349)) + 1352829926;
  v156 = v399 + ((32 * v155) | (v155 >> 27));
  v428 = (v152 << 10) | (v152 >> 22);
  v157 = v399 + v448 + (v156 ^ (v154 | ~v428)) + 1352829926;
  v158 = v349 + ((v157 << 7) | (v157 >> 25));
  v382 = (v154 << 10) | (v154 >> 22);
  v159 = v349 + v446 + (v158 ^ (v156 | ~v382)) + 1352829926;
  v160 = v428 + ((v159 << 7) | (v159 >> 25));
  v365 = (v156 << 10) | (v156 >> 22);
  v161 = v428 + v452 + (v160 ^ (v158 | ~v365)) + 1352829926;
  v162 = v382 + ((v161 << 8) | HIBYTE(v161));
  v400 = (v158 << 10) | (v158 >> 22);
  v163 = v382 + v444 + (v162 ^ (v160 | ~v400)) + 1352829926;
  v164 = v365 + ((v163 << 11) | (v163 >> 21));
  v350 = (v160 << 10) | (v160 >> 22);
  v165 = v365 + v8 + (v164 ^ (v162 | ~v350)) + 1352829926;
  v166 = v400 + ((v165 << 14) | (v165 >> 18));
  v429 = (v162 << 10) | (v162 >> 22);
  v167 = v400 + v441 + (v166 ^ (v164 | ~v429)) + 1352829926;
  v168 = v350 + ((v167 << 14) | (v167 >> 18));
  v383 = (v164 << 10) | (v164 >> 22);
  v169 = v350 + v10 + (v168 ^ (v166 | ~v383)) + 1352829926;
  v170 = v429 + ((v169 << 12) | (v169 >> 20));
  v366 = (v166 << 10) | (v166 >> 22);
  v171 = (unsigned __int64)(v429 + v440 + (v170 ^ (v168 | ~v366)) + 1352829926) << 6;
  v172 = v383 + (v171 | HIDWORD(v171));
  v401 = (v168 << 10) | (v168 >> 22);
  v384 = v366
       + (((v383 + v446 + (v172 & v401 | v170 & ~v401) + 1548603684) << 9) | ((v383
                                                                             + v446
                                                                             + (v172 & v401 | v170 & ~v401)
                                                                             + 1548603684) >> 23));
  v351 = (v170 << 10) | (v170 >> 22);
  v173 = v401
       + (((v366 + v451 + (v351 & v384 | v172 & ~v351) + 1548603684) << 13) | ((v366
                                                                              + v451
                                                                              + (v351 & v384 | v172 & ~v351)
                                                                              + 1548603684) >> 19));
  v430 = (v172 << 10) | (v172 >> 22);
  v174 = v351
       + (((v401 + v10 + (v430 & v173 | v384 & ~v430) + 1548603684) << 15) | ((v401
                                                                             + v10
                                                                             + (v430 & v173 | v384 & ~v430)
                                                                             + 1548603684) >> 17));
  v385 = (v384 << 10) | ((unsigned __int64)v384 >> 22);
  v175 = (unsigned __int64)(v351 + v445 + (v174 & v385 | v173 & ~v385) + 1548603684) << 7;
  v176 = v430 + (v175 | HIDWORD(v175));
  v367 = (v173 << 10) | (v173 >> 22);
  v177 = v430 + v5 + (v176 & v367 | v174 & ~v367) + 1548603684;
  v178 = (v177 << 12) | (v177 >> 20);
  v431 = v385 + v178;
  v402 = (v174 << 10) | (v174 >> 22);
  v179 = v385 + v448 + ((v385 + v178) & v402 | v176 & ~v402) + 1548603684;
  v180 = v367 + ((v179 << 8) | HIBYTE(v179));
  v352 = (v176 << 10) | (v176 >> 22);
  v181 = (v431 << 10) | ((unsigned __int64)v431 >> 22);
  v368 = v402
       + (((v367 + v443 + (v352 & v180 | v431 & ~v352) + 1548603684) << 9) | ((v367
                                                                             + v443
                                                                             + (v352 & v180 | v431 & ~v352)
                                                                             + 1548603684) >> 23));
  v182 = v352
       + (((v402 + v441 + (v181 & v368 | v180 & ~v181) + 1548603684) << 11) | ((v402
                                                                              + v441
                                                                              + (v181 & v368 | v180 & ~v181)
                                                                              + 1548603684) >> 21));
  v386 = (v180 << 10) | (v180 >> 22);
  v183 = v352 + v449 + (v182 & v386 | v368 & ~v386) + 1548603684;
  v184 = (v183 << 7) | (v183 >> 25);
  v353 = v181 + v184;
  v369 = (v368 << 10) | ((unsigned __int64)v368 >> 22);
  v185 = v181 + v452 + ((v181 + v184) & v369 | v182 & ~v369) + 1548603684;
  v186 = v386 + ((v185 << 7) | (v185 >> 25));
  v403 = (v182 << 10) | (v182 >> 22);
  v187 = v386 + v444 + (v186 & v403 | v353 & ~v403) + 1548603684;
  v188 = v369 + ((v187 << 12) | (v187 >> 20));
  v354 = (v353 << 10) | ((unsigned __int64)v353 >> 22);
  v189 = (unsigned __int64)(v369 + v440 + (v354 & v188 | v186 & ~v354) + 1548603684) << 7;
  v190 = (v186 << 10) | (v186 >> 22);
  v370 = v403 + (v189 | HIDWORD(v189));
  v191 = v403 + v442 + (v190 & v370 | v188 & ~v190) + 1548603684;
  v192 = v354 + ((v191 << 6) | (v191 >> 26));
  v387 = (v188 << 10) | (v188 >> 22);
  v193 = v354 + v450 + (v192 & v387 | v370 & ~v387) + 1548603684;
  v194 = (v193 << 15) | (v193 >> 17);
  v355 = v190 + v194;
  v371 = (v370 << 10) | ((unsigned __int64)v370 >> 22);
  v195 = v190 + v8 + ((v190 + v194) & v371 | v192 & ~v371) + 1548603684;
  v196 = v387 + ((v195 << 13) | (v195 >> 19));
  v404 = (v192 << 10) | (v192 >> 22);
  v197 = v387 + v447 + (v196 & v404 | v355 & ~v404) + 1548603684;
  v198 = v371 + ((v197 << 11) | (v197 >> 21));
  v356 = (v355 << 10) | ((unsigned __int64)(unsigned int)v355 >> 22);
  v199 = (unsigned __int64)(v371 + v452 + (v356 ^ (v198 | ~v196)) + 1836072691) << 9;
  v200 = v404 + (v199 | HIDWORD(v199));
  v432 = (v196 << 10) | (v196 >> 22);
  v201 = v404 + v443 + (v432 ^ (v200 | ~v198)) + 1836072691;
  v202 = v356 + ((v201 << 7) | (v201 >> 25));
  v388 = (v198 << 10) | (v198 >> 22);
  v203 = v356 + v8 + (v388 ^ (v202 | ~v200)) + 1836072691;
  v204 = v432 + ((v203 << 15) | (v203 >> 17));
  v372 = (v200 << 10) | (v200 >> 22);
  v205 = v432 + v10 + (v372 ^ (v204 | ~v202)) + 1836072691;
  v206 = v388 + ((v205 << 11) | (v205 >> 21));
  v405 = (v202 << 10) | (v202 >> 22);
  v207 = v388 + v445 + (v405 ^ (v206 | ~v204)) + 1836072691;
  v208 = v372 + ((v207 << 8) | HIBYTE(v207));
  v357 = (v204 << 10) | (v204 >> 22);
  v209 = v372 + v449 + (v357 ^ (v208 | ~v206)) + 1836072691;
  v210 = v405 + ((v209 << 6) | (v209 >> 26));
  v433 = (v206 << 10) | (v206 >> 22);
  v211 = v405 + v446 + (v433 ^ (v210 | ~v208)) + 1836072691;
  v212 = v357 + ((v211 << 6) | (v211 >> 26));
  v389 = (v208 << 10) | (v208 >> 22);
  v213 = v357 + v450 + (v389 ^ (v212 | ~v210)) + 1836072691;
  v214 = v433 + ((v213 << 14) | (v213 >> 18));
  v373 = (v210 << 10) | (v210 >> 22);
  v215 = v433 + v451 + (v373 ^ (v214 | ~v212)) + 1836072691;
  v216 = v389 + ((v215 << 12) | (v215 >> 20));
  v406 = (v212 << 10) | (v212 >> 22);
  v217 = v389 + v444 + (v406 ^ (v216 | ~v214)) + 1836072691;
  v218 = v373 + ((v217 << 13) | (v217 >> 19));
  v358 = (v214 << 10) | (v214 >> 22);
  v219 = v373 + v440 + (v358 ^ (v218 | ~v216)) + 1836072691;
  v220 = v406 + ((32 * v219) | (v219 >> 27));
  v434 = (v216 << 10) | (v216 >> 22);
  v221 = v406 + v447 + (v434 ^ (v220 | ~v218)) + 1836072691;
  v222 = v358 + ((v221 << 14) | (v221 >> 18));
  v390 = (v218 << 10) | (v218 >> 22);
  v223 = (unsigned __int64)(v358 + v441 + (v390 ^ (v222 | ~v220)) + 1836072691) << 13;
  v224 = v434 + (v223 | HIDWORD(v223));
  v374 = (v220 << 10) | (v220 >> 22);
  v225 = v390
       + (((v434 + v5 + (v374 ^ (v224 | ~v222)) + 1836072691) << 13) | ((v434 + v5 + (v374 ^ (v224 | ~v222)) + 1836072691) >> 19));
  v407 = (v222 << 10) | (v222 >> 22);
  v226 = v390 + v442 + (v407 ^ (v225 | ~v224)) + 1836072691;
  v227 = v374 + ((v226 << 7) | (v226 >> 25));
  v359 = (v224 << 10) | (v224 >> 22);
  v228 = v407
       + ((32 * (v374 + v448 + (v359 ^ (v227 | ~v225)) + 1836072691)) | ((v374
                                                                        + v448
                                                                        + (v359 ^ (v227 | ~v225))
                                                                        + 1836072691) >> 27));
  v435 = (v225 << 10) | (v225 >> 22);
  v229 = v359
       + (((v407 + v444 + (v228 & v227 | v435 & ~v228) + 2053994217) << 15) | ((v407
                                                                              + v444
                                                                              + (v228 & v227 | v435 & ~v228)
                                                                              + 2053994217) >> 17));
  v391 = (v227 << 10) | (v227 >> 22);
  v230 = v435
       + ((32 * (v359 + v446 + (v229 & v228 | v391 & ~v229) + 2053994217)) | ((v359
                                                                             + v446
                                                                             + (v229 & v228 | v391 & ~v229)
                                                                             + 2053994217) >> 27));
  v375 = (v228 << 10) | (v228 >> 22);
  v231 = v435 + v442 + (v230 & v229 | v375 & ~v230) + 2053994217;
  v232 = v391 + ((v231 << 8) | HIBYTE(v231));
  v408 = (v229 << 10) | (v229 >> 22);
  v233 = v391 + v8 + (v232 & v230 | v408 & ~v232) + 2053994217;
  v234 = v375 + ((v233 << 11) | (v233 >> 21));
  v360 = (v230 << 10) | (v230 >> 22);
  v235 = v375 + v10 + (v232 & v234 | v360 & ~v234) + 2053994217;
  v236 = v408 + ((v235 << 14) | (v235 >> 18));
  v436 = (v232 << 10) | (v232 >> 22);
  v237 = v408 + v451 + (v236 & v234 | v436 & ~v236) + 2053994217;
  v238 = v360 + ((v237 << 14) | (v237 >> 18));
  v392 = (v234 << 10) | (v234 >> 22);
  v239 = v360 + v452 + (v238 & v236 | v392 & ~v238) + 2053994217;
  v240 = v436 + ((v239 << 6) | (v239 >> 26));
  v376 = (v236 << 10) | (v236 >> 22);
  v241 = v436 + v5 + (v240 & v238 | v376 & ~v240) + 2053994217;
  v242 = v392 + ((v241 << 14) | (v241 >> 18));
  v409 = (v238 << 10) | (v238 >> 22);
  v243 = v392 + v443 + (v242 & v240 | v409 & ~v242) + 2053994217;
  v244 = v376 + ((v243 << 6) | (v243 >> 26));
  v361 = (v240 << 10) | (v240 >> 22);
  v245 = v376 + v440 + (v242 & v244 | v361 & ~v244) + 2053994217;
  v246 = v409 + ((v245 << 9) | (v245 >> 23));
  v437 = (v242 << 10) | (v242 >> 22);
  v247 = v409 + v447 + (v246 & v244 | v437 & ~v246) + 2053994217;
  v248 = v361 + ((v247 << 12) | (v247 >> 20));
  v393 = (v244 << 10) | (v244 >> 22);
  v249 = v361 + v448 + (v248 & v246 | v393 & ~v248) + 2053994217;
  v250 = v437 + ((v249 << 9) | (v249 >> 23));
  v377 = (v246 << 10) | (v246 >> 22);
  v251 = v437 + v450 + (v250 & v248 | v377 & ~v250) + 2053994217;
  v252 = v393 + ((v251 << 12) | (v251 >> 20));
  v410 = (v248 << 10) | (v248 >> 22);
  v253 = v393 + v445 + (v252 & v250 | v410 & ~v252) + 2053994217;
  v254 = v377 + ((32 * v253) | (v253 >> 27));
  v362 = (v250 << 10) | (v250 >> 22);
  v255 = v377 + v441 + (v252 & v254 | v362 & ~v254) + 2053994217;
  v256 = v410 + ((v255 << 15) | (v255 >> 17));
  v438 = (v252 << 10) | (v252 >> 22);
  v257 = v362
       + (((v410 + v449 + (v256 & v254 | v438 & ~v256) + 2053994217) << 8) | ((v410
                                                                             + v449
                                                                             + (v256 & v254 | v438 & ~v256)
                                                                             + 2053994217) >> 24));
  v394 = (v254 << 10) | (v254 >> 22);
  v258 = v438 + (((v440 + (v257 ^ v256 ^ v394) + v362) << 8) | ((v440 + (v257 ^ v256 ^ v394) + v362) >> 24));
  v378 = (v256 << 10) | (v256 >> 22);
  v259 = 32i64 * (v452 + (v258 ^ v257 ^ v378) + v438);
  v260 = v394 + (v259 | HIDWORD(v259));
  v411 = (v257 << 10) | (v257 >> 22);
  v261 = (unsigned __int64)(v441 + (v260 ^ v258 ^ v411) + v394) << 12;
  v262 = v378 + (v261 | HIDWORD(v261));
  v363 = (v258 << 10) | (v258 >> 22);
  v263 = v411 + (((v442 + (v260 ^ v363 ^ v262) + v378) << 9) | ((v442 + (v260 ^ v363 ^ v262) + v378) >> 23));
  v264 = (v260 << 10) | (v260 >> 22);
  v265 = v363 + (((v8 + (v264 ^ v263 ^ v262) + v411) << 12) | ((v8 + (v264 ^ v263 ^ v262) + v411) >> 20));
  v395 = (v262 << 10) | (v262 >> 22);
  v266 = 32i64 * (v443 + (v265 ^ v263 ^ v395) + v363);
  v267 = (v263 << 10) | (v263 >> 22);
  v268 = v264 + (v266 | HIDWORD(v266));
  v269 = v395 + (((v444 + (v268 ^ v265 ^ v267) + v264) << 14) | ((v444 + (v268 ^ v265 ^ v267) + v264) >> 18));
  v412 = (v265 << 10) | (v265 >> 22);
  v270 = (unsigned __int64)(v445 + (v269 ^ v268 ^ v412) + v395) << 6;
  v271 = v267 + (v270 | HIDWORD(v270));
  v272 = (v268 << 10) | (v268 >> 22);
  v273 = v412 + (((v446 + (v269 ^ v272 ^ v271) + v267) << 8) | ((v446 + (v269 ^ v272 ^ v271) + v267) >> 24));
  v439 = (v269 << 10) | (v269 >> 22);
  v274 = (v271 << 10) | (v271 >> 22);
  v275 = v272 + (((v447 + (v439 ^ v273 ^ v271) + v412) << 13) | ((v447 + (v439 ^ v273 ^ v271) + v412) >> 19));
  v276 = v439 + (((v448 + (v275 ^ v273 ^ v274) + v272) << 6) | ((v448 + (v275 ^ v273 ^ v274) + v272) >> 26));
  v379 = (v273 << 10) | (v273 >> 22);
  v277 = 32i64 * (v449 + (v276 ^ v275 ^ v379) + v439);
  v278 = (v275 << 10) | (v275 >> 22);
  v279 = v274 + (v277 | HIDWORD(v277));
  v280 = v379 + (((v5 + (v279 ^ v276 ^ v278) + v274) << 15) | ((v5 + (v279 ^ v276 ^ v278) + v274) >> 17));
  v281 = (v276 << 10) | (v276 >> 22);
  v282 = (v279 << 10) | (v279 >> 22);
  v283 = v278 + (((v10 + (v279 ^ v281 ^ v280) + v379) << 13) | ((v10 + (v279 ^ v281 ^ v280) + v379) >> 19));
  v284 = v281 + (((v450 + (v282 ^ v283 ^ v280) + v278) << 11) | ((v450 + (v282 ^ v283 ^ v280) + v278) >> 21));
  v396 = (v280 << 10) | (v280 >> 22);
  v285 = v451 + (v284 ^ v283 ^ v396) + v281;
  v286 = v347 + a1[1] + ((v283 << 10) | (v283 >> 22));
  v287 = a1[3];
  a1[1] = v396 + a1[2] + ((v310 << 10) | ((unsigned __int64)v310 >> 22));
  a1[2] = v329 + v282 + v287;
  a1[3] = v425 + v282 + a1[4] + ((v285 << 11) | (v285 >> 21));
  v288 = *a1 + ((v473 << 6) | ((unsigned __int64)v473 >> 26));
  *a1 = v286;
  a1[4] = v425 + v284 + v288;
}

//----- (00002310) --------------------------------------------------------
void __cdecl MDfinish(unsigned int *a1, unsigned __int8 *a2, unsigned int a3, unsigned int a4)
{
  unsigned int v4; // eax
  unsigned int v5; // edi
  unsigned int *v7; // esi
  int v8; // ecx
  unsigned int v9[16]; // [esp+Ch] [ebp-40h] BYREF

  v4 = 0;
  memset(v9, 0, sizeof(v9));
  v5 = a3 & 0x3F;
  if ( (a3 & 0x3F) != 0 )
  {
    do
    {
      v7 = &v9[v4 >> 2];
      v8 = (*a2++ << (8 * (v4++ & 3))) ^ *v7;
      *v7 = v8;
    }
    while ( v4 < v5 );
  }
  v9[(a3 >> 2) & 0xF] ^= 1 << (8 * (a3 & 3) + 7);
  if ( v5 > 0x37 )
  {
    MDcompress(a1, v9);
    memset(v9, 0, sizeof(v9));
  }
  *(_QWORD *)&v9[14] = 8 * __PAIR64__(a4, a3);
  MDcompress(a1, v9);
}

//----- (000023E0) --------------------------------------------------------
unsigned __int8 *__cdecl MDbinary(LPCSTR lpFileName)
{
  HANDLE v1; // esi
  unsigned int v2; // ebx
  DWORD v3; // eax
  DWORD v4; // ebp
  char *v5; // esi
  unsigned int *v6; // eax
  int v7; // edi
  unsigned __int16 v8; // dx
  int v9; // ecx
  unsigned int v10; // eax
  unsigned int j; // eax
  unsigned int v12; // ecx
  unsigned int v13; // ecx
  DWORD NumberOfBytesRead[2]; // [esp+4h] [ebp-464h] BYREF
  unsigned int i; // [esp+Ch] [ebp-45Ch]
  HANDLE v17; // [esp+10h] [ebp-458h]
  unsigned int v18[5]; // [esp+14h] [ebp-454h] BYREF
  unsigned int v19[16]; // [esp+28h] [ebp-440h] BYREF
  unsigned __int8 Buffer[2]; // [esp+68h] [ebp-400h] BYREF
  char v21; // [esp+6Ah] [ebp-3FEh] BYREF

  _hashcode__1__MDbinary__YAPAEPBD_Z_4PAEA[0] = 0;
  dword_2574 = 0;
  dword_2578 = 0;
  dword_257C = 0;
  dword_2580 = 0;
  v1 = CreateFileA(lpFileName, 0x80000000, 1u, 0, 3u, 0x8000027u, 0);
  v17 = v1;
  if ( v1 != (HANDLE)-1 )
  {
    MDinit(v18);
    v2 = 0;
    for ( i = 0; ReadFile(v1, Buffer, 0x400u, NumberOfBytesRead, 0); v2 = v10 )
    {
      v3 = NumberOfBytesRead[0];
      if ( !NumberOfBytesRead[0] )
        break;
      v4 = 0;
      if ( (NumberOfBytesRead[0] & 0xFFFFFFC0) != 0 )
      {
        v5 = &v21;
        do
        {
          v6 = v19;
          v7 = 16;
          do
          {
            v8 = *(_WORD *)v5;
            v9 = (unsigned __int8)*(v5 - 1);
            v5 += 4;
            ++v6;
            --v7;
            *(v6 - 1) = (unsigned __int8)*(v5 - 6) | ((v9 | (v8 << 8)) << 8);
          }
          while ( v7 );
          MDcompress(v18, v19);
          v3 = NumberOfBytesRead[0];
          ++v4;
        }
        while ( v4 < NumberOfBytesRead[0] >> 6 );
        v1 = v17;
      }
      v10 = v2 + v3;
      if ( v10 < v2 )
        ++i;
    }
    MDfinish(v18, &Buffer[v2 & 0x3C0], v2, i);
    for ( j = 0; j < 5; HIBYTE(_hashcode__1__MDbinary__YAPAEPBD_Z_4PAEA[j - 1]) = HIBYTE(v13) )
    {
      v12 = j * 4;
      ++j;
      v12 >>= 2;
      LOBYTE(_hashcode__1__MDbinary__YAPAEPBD_Z_4PAEA[j - 1]) = v18[v12];
      v13 = v18[v12];
      BYTE1(_hashcode__1__MDbinary__YAPAEPBD_Z_4PAEA[j - 1]) = BYTE1(v13);
      BYTE2(_hashcode__1__MDbinary__YAPAEPBD_Z_4PAEA[j - 1]) = BYTE2(v13);
    }
    CloseHandle(v1);
  }
  return (unsigned __int8 *)_hashcode__1__MDbinary__YAPAEPBD_Z_4PAEA;
}
// 2570: using guessed type int _hashcode__1__MDbinary__YAPAEPBD_Z_4PAEA[];
// 2574: using guessed type int dword_2574;
// 2578: using guessed type int dword_2578;
// 257C: using guessed type int dword_257C;
// 2580: using guessed type int dword_2580;

// nfuncs=7 queued=4 decompiled=4 lumina nreq=0 worse=0 better=0
// ALL OK, 4 function(s) have been successfully decompiled
